### DISCUSSION TITLE
How to send mail using port 587 or 2525

### DISCUSSION THREAD

**Discussion by bablukumarmaharana** [postalserver/postal#1457] [Help with using Postal]
Hey,
My service provider block my **port 25**. So I got execution expired error.

How can I send by using **port 587 or 2525**?

Because some person send mail by using port 587. 
Anyone help me?

**Comment by willpower232** [comment]
You can change the port in the config file however if you are unable to receive email on port 25, it is likely you will have problems receiving bouncebacks and other messages and your server provider may already block the other email ports so you should either ask your provider to allow you to use those ports or move provider.

**Comment by bablukumarmaharana** [comment]
Hey @willpower232 

I have already checked port 587 and 2525 is open for mailing. They are deny for open port 25.

Just guide me how to change the port 25 to 587. 

I don't want to receive bouncebacks and other messages. I will handle this by webhook or other method.

**Comment by willpower232** [comment]
The bouncebacks may not make it to your Postal server if you don't have port 25 so you wouldn't get webhooks triggered.

The port is in the config file.

**Comment by bablukumarmaharana** [comment]
@willpower232 
If I change this in config file,

smtp:
  host: 127.0.0.1
  port: 587
  username:
  password:
  from_name: Postal
  from_address: postal@yourdomain.com
  
smtp_server:
  port: 587
  
It doesn't work for me.It's show error failed to connect smtp

**Comment by willpower232** [comment]
Did you restart Postal to apply the config file changes?

You can also use `sudo netstat -lnp` to verify which port is being used (and what is listening on it)

**Comment by dragoangel** [comment]
My suggestion is: https://github.com/postalserver/postal/discussions/1517

**Comment by JasonDevTech** [comment]
If I wanted to send on port 587 and receive on port 25, then would my config look like this? `587` for `smtp_server` and `25` for `smtp_relay`?

```yaml
smtp_server:
  port: 587
  bind_address: '::'
  tls_enabled: false
  tls_certificate_path: # Defaults to config/smtp.cert
  tls_private_key_path: # Defaults to config/smtp.key
  tls_ciphers:
  ssl_version: SSLv23
  proxy_protocol: false
  log_connect: true
  strip_received_headers: false
  max_message_size: 14 # size in Megabytes

smtp_relays:
  -
    hostname:
    port: 25
    ssl_mode: Auto
```
