### DISCUSSION TITLE
SSL_connect returned=1 errno=0 state=error: dh key too small

### DISCUSSION THREAD

**Discussion by quorak** [postalserver/postal#1558] [Feature suggestions]
I get the hard bounce error for sending emails to some mail servers.

I found the solution here: https://github.com/postalserver/postal/issues/943
I am using the new postal installation method with a docker-compose. 
Is there a way to set this values to inside the container?
`RUN sed -i -e "s/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/" /etc/ssl/openssl.cnf`

thanks a lot

**Comment by quorak** [comment]
### Workaround for now:

Create Dockerfile with:
```Dockerfile
FROM ghcr.io/postalserver/postal:2.0.0
USER root
RUN sed -i -e "s/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/" /etc/ssl/openssl.cnf
USER postal
```

Create new container with fix, set postal version to new container. restart.
```bash
docker build -t ghcr.io/postalserver/postal:2.0.0.fix .
postal set-version 2.0.0.fix
postal stop
postal start
```

**Reply by July250229** [reply]
Thank you for your detailed tutorial. This works well with the latest version 2.1.1. The queued messages due to this problem can be sent now.

**Comment by Joe-Ng-1998** [comment]
Please push a new docker image to fix this issue.

**Reply by casualmatt** [reply]
I have the same issue is possible to have that fix on the main image?

**Reply by pjv** [reply]
An alternative to an image update is to bind-mount a customized version of the `openssl.cnf` file into the `smtp` and `worker` containers.

If running a standard install of Postal v.2, you can create a `docker-compose-override.yml` file in `/opt/postal/install/` with something like this in it:

````
smtp:
    volumes:
      - /opt/postal/config:/config
      - /opt/postal/config/ssl/openssl/openssl.cnf:/etc/ssl/openssl.cnf

worker:
    volumes:
      - /opt/postal/config:/config
      - /opt/postal/config/ssl/openssl/openssl.cnf:/etc/ssl/openssl.cnf
````

You can bash into the smtp container (`postal bash smtp`) to make a copy of the original `openssl.cnf` file and then put it somewhere on your host (I've put it in `/opt/postal/config/ssl/openssl/openssl.cnf`) with the necessary modifications.

**Reply by cameronbraid** [reply]
good idea, thanks

**Reply by littleearth** [reply]
Forgive me if this is not the correct way, but it was how I got it working

I do not see how postal applies docker-compose-override.yml if you look at the postal start command it just issues the following command 
docker-compose -p postal up -d 

So using the above as a hint

create /opt/postal/install/docker-compose-override.yml (Note: missing version and service values)

```
version: "3.9"
services:
  smtp:
    volumes:
      - /opt/postal/config:/config
      - /opt/postal/config/ssl/openssl/openssl.cnf:/etc/ssl/openssl.cnf

  worker:
    volumes:
      - /opt/postal/config:/config
      - /opt/postal/config/ssl/openssl/openssl.cnf:/etc/ssl/openssl.cnf
```

Run the following commands

```
postal stop
cp docker-compose.yml docker-compose-backup.yml
docker-compose -f docker-compose.yml -f docker-compose-override.yml config >> docker-compose.yml
postal start
```
