### DISCUSSION TITLE
How to use the Certificate Caddy in Tls

### DISCUSSION THREAD

**Discussion by raf-rodrigues** [postalserver/postal#1572] [Help with using Postal] [answered]
I am trying to use TLs for Smtp. But how to use the caddy generated certificates that are located in the folder /opt/postal/caddy-data/

I tried to indicate them directly in the config file, but the smtp log shows that it can't read them. 

I made a copy to the /config folder and the same error. 

What would be the solution to use these certificates?

**Comment by solracsf** [comment, marked as answer]
As Caddy generates ECC certs (to be confirmed) it should not be possible because of https://github.com/postalserver/postal/issues/1248

**Reply by raf-rodrigues** [reply]
Yeah I figured it was something like that.

First I stopped the Caddy and Postal containers, installed Certbot and generated a certificate for the server. I copied the Private and full certificates to the /config folder and indicated it in the configuration file.

I reactivated the containers and TLS works.

**Reply by sergioloera** [reply]
I installed certbot, generated the cert and copied the cert and privkey to the /config folder in the  and updated the postal.yml to reflect: 

```
smtp_server:
  # Specify configuration to the Postal SMTP server
  port: 25
  tls_enabled: true
  tls_certificate_path: /opt/postal/config/fullchain.pem
  tls_private_key_path: /opt/postal/config/privkey.pem
```

then, restarted. even the whole thing and nothing. What am I missing?
