### DISCUSSION TITLE
How to support SSLv3

### DISCUSSION THREAD

**Discussion by solracsf** [postalserver/postal#1584] [Help with using Postal] [answered]
Some servers requires SSLv3, like exposed at https://github.com/postalserver/postal/issues/982#issuecomment-911777574 or:

```
worker_1    | INFO -- : [CMW7YKXO] Cannot connect to 193.252.22.65:25 (smtp-in.orange.fr) (OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: unsupported protocol)
worker_1    | INFO -- : [CMW7YKXO] -> No SMTP server available for wanadoo.fr
worker_1    | INFO -- : [CMW7YKXO] -> Hostnames: ["smtp-in.orange.fr"]
worker_1    | INFO -- : [CMW7YKXO] -> Errors: ["SSL_connect returned=1 errno=0 state=error: unsupported protocol"]
```

How can we add support on this with Postal v2?

**Comment by willpower232** [comment]
Have you configured these away from SSLv23?

https://github.com/postalserver/postal/blob/d808d15c28d1c4c626af44bedc05743b01e078b9/config/postal.defaults.yml#L67-L68

**Reply by solracsf** [reply]
Not explicitly, so the default should apply, no?

```
smtp_server:
  tls_enabled: true
  tls_certificate_path: /config/fullchain.pem
  tls_private_key_path: /config/certkey.key
```
