### DISCUSSION TITLE
Is customizing the v2 docker-compose.yml file upgrade safe?

### DISCUSSION THREAD

**Discussion by pjv** [postalserver/postal#1637] [Help with using Postal]
If I follow the [install instructions](https://docs.postalserver.io/install/installation/), I end up with a `docker-compose.yml` file at `/opt/postal/install/docker-compose.yml` which is referenced by the `postal` command.

If I were to customize this `docker-compose.yml` file (e.g. let’s say that I want more than one worker container, which anyone who is running more than a toy install would need to do, so I am supplying a `scale: 8` in the `worker` service. Or say I want to be able to start and stop the full necessary stack for actually, you know, _running_ postal so I add services to bring up containers for mariadb, rabbitmq, and caddy along with what’s necessary to make sure they are initialized before the postal containers come up), would my `docker-compose.yml` customizations survive future upgrades via the command `postal upgrade`?

**Comment by willpower232** [comment]
You can see in https://github.com/postalserver/install/blob/main/bin/postal that a backup is made of the docker-compose.yml file so it is not completely safe but you will not totally lose everything.

It is probably something that should be resolved at some point but that depends on what upgrades are necessary to the docker-compose file in the future I guess

**Reply by pjv** [reply]
> It is probably something that should be resolved at some point but that depends on what upgrades are necessary to the docker-compose file in the future I guess

With the logic in the v2 `postal` command, every `upgrade` (as well as every `set-version`) un-does any customizations made to the docker-compose file and would require manually re-merging any necessary customizations after the upgrade (or set-version). Yet at the same time, some customizations (at the very least setting a `scale` for the number of worker processes) is an absolute requirement for running postal at anything beyond a proof of concept volume level.

So it seems to me that the deployment and upgrade concept for postal v2 is not fully implemented yet.

There are any number of different ways to create an upgrade-friendly docker deployment. Using a `docker-compose.override.yml` is one that many projects use. Since running Postal as more than a proof of concept service requires customizing, it seems like a recommended path of customization should be covered and exemplified in the documentation.

**Reply by willpower232** [reply]
This is a great idea, I haven't managed to use an override yet since I want it to use different options and not merge them together but in this case, the only change would be adding the file to the `.gitignore` in the installation repo so that it wasn't changed by git at any point.

**Reply by pjv** [reply]
If and when I get a chance to really test running under the `docker-compose.override.yml` shown below, I could create a PR that would include it in the examples directory - though the length of time that most PR’s seem to spend waiting for review in Postal is a bit daunting.

**Comment by pjv** [comment]
Here is a very slightly tested (it comes up, logs reasonable stuff, and brings up the Postal UI - I don’t know if it sends emails yet and YMMV) `docker-compose.override.yml` which allows Postal to run on a VPS that has docker and docker-compose installed. If following the [Postal install instructions](https://docs.postalserver.io/install/installation/), you would omit the manual docker commands to bring up mariadb, rabbitmq and caddy and instead copy this file to `/opt/postal/install` (or in any case sit it next to the postal `docker-compose.yml`). 

In addition to providing Postal’s hard dependencies, this is also an alternative (to using systemd) solution to #1610 (restarting Postal automatically on reboot).

@jaydrogers, this is a further refinement of the discussion in #1421.

[As an aside, I really think it would be a lot better for the project (read: cut down on basic support requests) if the developers supplied a fully working canonical VPS implementation for postal and didn’t leave it to punters (like myself) to supply this. Yes, there are infinite ways to deploy Postal and to provide for the hard dependencies (db, web proxy, mq), but exploring those infinities should be left as an exercise for advanced sysadmins and devops engineers. There should be a minimal, _fully working_, canonical Postal configuration for users to start with.]

````
version: "3.9"
services:
  caddy:
    image: caddy:alpine
    container_name: postal-caddy
    restart: unless-stopped
    network_mode: host # using ip pools
    volumes:
      - /opt/postal/config/Caddyfile:/etc/caddy/Caddyfile
      - /opt/postal/caddy-data:/data

  mariadb:
    image: mariadb:10.3 # most recent mariadb version that didn’t choke for me on migrating v1 db to v2
    container_name: postal-mariadb
    restart: unless-stopped
    ports:
      - "127.0.0.1:3306:3306"
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-u', 'root', '-p<SECRET>’ ]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      MARIADB_DATABASE: postal
      MARIADB_ROOT_PASSWORD: <SECRET>
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
      - ./conf.d:/etc/mysql/conf.d # place any custom mysql / mariadb configuration files (ending .cnf) here
      - dbdata:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3.9
    container_name: postal-rabbitmq
    restart: unless-stopped
    ports:
      - "127.0.0.1:5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      RABBITMQ_DEFAULT_USER: postal
      RABBITMQ_DEFAULT_PASS: <SECRET>
      RABBITMQ_DEFAULT_VHOST: postal
    volumes:
      - mqdata:/var/lib/rabbitmq/mnesia/

  web: &postal
    restart: unless-stopped
    depends_on:
      - mariadb
      - rabbitmq
    environment:
      WAIT_FOR_TARGETS: 127.0.0.1:3306 127.0.0.1:5672
      WAIT_FOR_TIMEOUT: 90

  smtp:
    <<: *postal

  worker:
    <<: *postal
    scale: 8 # adjust for the server resources available and needed

  cron:
    <<: *postal

  requeuer:
    <<: *postal

  runner:
    <<: *postal

volumes:
  dbdata:
  mqdata:
````
