### DISCUSSION TITLE
Tracking stopped working after upgrade

### DISCUSSION THREAD

**Discussion by uhlhosting** [postalserver/postal#1675] [Help with using Postal]
What changed in postal 2.0 since it was mentioned is not needed an additional ip for tracking.

https://seen.uhl.cloud/nk4d3v/Zr7lVPGW same as bellow the results, yet there are no issues with ssl while uhl.cloud has ssl issues.

One example, first I am wondering how I enable the SSL for the tracking domain, since havent seen this documented.

https://click.uhl.site/nk4d3v/fYgbPNgb gets me:

<img width="653" alt="image" src="https://user-images.githubusercontent.com/6324047/139574631-71fe4b63-3b98-45c1-9d6c-902e879afb6b.png">

https://idm.pac.uhl.cloud/auth/realms/master/login-actions/action-token?key=eyJhbGciO.............. This or simillar to this must be behind the click link. Any idea why this is not working as expected.

Here its my current config for DNS in Postal

 ```
 mx_records:
    - "post.uhlhosting.ch"
  smtp_server_hostname: "post.uhlhosting.ch"
  spf_include: "spf.post.uhlhosting.ch"
  return_path: "rp.post.uhlhosting.ch"
  route_domain: "routes.post.uhlhosting.ch"
  track_domain: "post.uhlhosting.ch"
  dkim_identifier: postal
  domain_verify_prefix: postal-verification
  custom_return_path_prefix: psrp
```
