### DISCUSSION TITLE
Build Mail server [Error 500]

### DISCUSSION THREAD

**Discussion by medito** [postalserver/postal#1784] [Help with using Postal] [answered]
Hello,
I tried to install **Postal** on my server **Debian 11**.
My DNS config for postal is : 
```  
dns:
  mx_records: 
    - mx1.mail.XYZ.com
  smtp_server_hostname: mail.XYZ.com \
  spf_include: spf.mail.XYZ.com
  return_path: rp.mail.XYZ.com
  route_domain: routes.mail.XYZ.com
  track_domain: track.mail.XYZ.com
```
The Organization was created without any Error.
But when I want to create the mail server the button **Build server** is frozen, and only there is one error : 
`web_1       | 10.0.4.254 - - [24/Dec/2021:19:20:59 +0000] "POST /500 HTTP/1.1" 500 46 0.0368`

Someone can help me please.

Thank you.
