### DISCUSSION TITLE
Spam check is not working anymore since upgrade to version 2.x

### DISCUSSION THREAD

**Discussion by uhlhosting** [postalserver/postal#1853] [Help with using Postal]
<img width="611" alt="image" src="https://user-images.githubusercontent.com/6324047/153209083-b05e0014-7c43-450c-9809-786eef1bec89.png">
this is only shown now. 

Our config has:

```
#rspamd:
#  enabled: false
#  host: 127.0.0.1
#  port: 11334
#  ssl: false
#  password: null
#  flags: null

spamd:
  enabled: true
  host: 127.0.0.1
  port: 783

clamav:
  enabled: false
  host: 127.0.0.1
  port: 2000
```
