### DISCUSSION TITLE
Allow different hosts to connect to Postal web server (fix 'Connection refused')

### DISCUSSION THREAD

**Discussion by danielboven** [postalserver/postal#1883] [Help with using Postal] [answered]
## Situation
I have a Postal installation running on a server with the Postal web server bound to `127.0.0.1:5000`. On this same server, I use Docker to launch (among other things) a small queue worker that sends transactional emails to Postal using the API. Besides the Docker containers, I run two applications (primarily) outside of Docker:
- postal
- nginx

This means that the Docker queue container should connect to Postal using a host network (the network of the machine). The `docker-compose.yml` file therefore looks like this:

```
version: "3"
services:
  queue-workers:
    build: .
    env_file:
      - ./.env
    depends_on:
      - mongo
      - redis
    command: npm run start:workers
    extra_hosts:
      - "host.docker.internal:host-gateway"
```
The `host.docker.internal:host-gateway` ensures that the localhost endpoints on the machine are routed to `host.docker.internal` and can thus be used inside a Docker container (which uses a bridge network). 

This extra host seems to allow the Docker container to connect to different localhost endpoints, such as nginx. **However, `host.docker.internal:host-gateway` does not allow the Docker container to connect to the Postal web server**, since it results in `ECONNREFUSED` errors. More information is given below at the examples.

## Installation
My current installation started on Postal v1. Using [this documentation](https://docs.postalserver.io/install/upgrade-to-v2), I upgraded my current installation to Postal v2. I have used the `docker-compose.yml` from the [postalserver/install](https://github.com/postalserver/install/) repository.
This is the content of the `/opt/postal/config/postal.yml` file:

```
general:
  # This can be changed to allow messages to be sent from multiple IP addresses
  use_ip_pools: false

web:
  # The host that the management interface will be available on
  host: postal.myowndomain.nl
  # The protocol that requests to the management interface should happen on
  protocol: https

web_server:
  # Specify configuration for the Postal web server
  bind_address: 127.0.0.1
  port: 5000

smtp_server:
  # Specify configuration to the Postal SMTP server
  port: 25

logging:
  # Specify options for the logging
  stdout: true

main_db:
  # Specify the connection details for your MySQL database
  host: 127.0.0.1
  username: root
  password: myFirstDatabasePassword
  database: postal

message_db:
  # Specify the connection details for your MySQL server that will be house the
  # message databases for mail servers.
  host: 127.0.0.1
  username: root
  password: mySecondDatabasePassword
  prefix: postal

rabbitmq:
  # Specify connection details for your RabbitMQ server
  host: 127.0.0.1
  username: postal
  password: myRabbitPassword
  vhost: postal

dns:
  # Specify the DNS records that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - postal.myowndomain.nl
  smtp_server_hostname: postal.myowndomain.nl
  spf_include: spf.postal.myowndomain.nl
  return_path: rp.postal.myowndomain.nl
  route_domain: routes.postal.myowndomain.nl
  track_domain: click.postal.myowndomain.nl

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 127.0.0.1
  port: 2525
  username: # Complete when Postal is running and you can
  password: # generate the credentials within the interface.
  from_name: Postal
  from_address: postal.myowndomain.nl

rails:
  # This is generated automatically by the config initialization. It should be a random
  # string unique to your installation.
  secret_key: myOwnKey
```

## Examples (in Docker)
_After spinning up the container, I used `docker container exec -it mydashboard_queue-workers_1 bash` to execute the commands below._

The following example (run on the queue Docker container) illustrates the problem:
```
$ wget http://host.docker.internal:5000
Resolving host.docker.internal (host.docker.internal)... 172.17.0.1
Connecting to host.docker.internal (host.docker.internal)|172.17.0.1|:5000... failed: Connection refused.
```

On the other hand, connecting to the Postal web server in the usual manner means the domain name points to `127.0.0.1`, which in a Docker container (bridge network) is not the same localhost as in the host network. I therefore get the following result:
```
$ wget https://postal.myowndomain.nl
Resolving postal.myowndomain.nl (postal.myowndomain.nl)... 127.0.0.1
Connecting to postal.myowndomain.nl (postal.myowndomain.nl)|127.0.0.1|:443... failed: Connection refused.
```

The second application I run outside of Docker is nginx. It does not seem to have any problem with the `host.docker.internal` name. For instance, firing a request from the Docker queue container gives a result that is exactly as expected:
```
$ wget http://host.docker.internal:80 
Resolving host.docker.internal (host.docker.internal)... 172.17.0.1
Connecting to host.docker.internal (host.docker.internal)|172.17.0.1|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
... (etc.)
```

## Reproduce (with examples)
A much easier way to reproduce the error without Docker is to add a new loopback interface with another IP address to the machine:
`sudo ifconfig lo:0 127.0.0.2 netmask 255.0.0.0 up`

The new IP address `127.0.0.2` _does_ work with services like nginx, but _does not_ with Postal. Refer to the following output:

```
$ wget 127.0.0.2:5000
--2022-03-01 08:21:28--  http://127.0.0.2:5000/
Connecting to 127.0.0.2:5000... failed: Connection refused.
```

Working with nginx:
```
$ wget 127.0.0.2
http://127.0.0.2/
Connecting to 127.0.0.2:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
... (etc.)
```

## Question
Based on the examples, the Postal web server only seems to accept/listen to selected addresses, since different addresses pointing to localhost are not accepted.

I therefore have the following question: is it possible to make a modification to (the configuration of) Postal in order to allow different internal addresses to connect to the Postal web server (such as allowing `host.docker.internal` or `172.17.0.1`)?

**Comment by danielboven** [comment, marked as answer]
It turns out the answer to my question is easier than I had thought. I do not know a lot about networking, but today I learned that [if you are binding to localhost (i.e. 127.0.0.1), you can only accept connections from the localhost, not over the network](https://stackoverflow.com/a/24057311). This seems intuitive, but therefore also means that the internal address `host.docker.internal` is not accepted.

An easy solution is to bind to all interfaces instead, meaning to `0.0.0.0`. This can be achieved by changing the `/opt/postal/config/postal.yml` file:

```
web_server:
  # Specify configuration for the Postal web server
  bind_address: 0.0.0.0
  port: 5000
```

After having changed the web_server configuration and restarting Postal, the Docker container was perfectly able to connect to Postal through `host.docker.internal`. Moreover, `127.0.0.1` also still points to the Postal web server on port 5000.
I am not sure if there is a better solution to the problem, but for now this seems to be my best bet.
