### DISCUSSION TITLE
Postal and Chatwoot SMTP

### DISCUSSION THREAD

**Discussion by uhlhosting** [postalserver/postal#1941] [Help with using Postal] [answered]
Did someone using Chatwoot, has managed to get it working with postal?

https://www.chatwoot.com/docs/self-hosted/configuration/environment-variables#configure-emails
It seems there is a hint from the worker in chatwoot I found this:

```
2022-04-05T17:39:41.255363571Z E, [2022-04-05T17:39:41.255203 #1] ERROR -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [bfbb2136-ce61-4564-bb5d-4f103a49e4de] Error performing ActionMailer::MailDeliveryJob (Job ID: bfbb2136-ce61-4564-bb5d-4f103a49e4de) from Sidekiq(mailers) in 4.98ms: ActionView::Template::Error (Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true):
```

**Comment by willpower232** [comment]
After you set up an SMTP credential, you can provide the appropriate environment variables it seems.

**Reply by uhlhosting** [reply]
Yes, just until now havent figured out why is not working, since we provided all required variables.

**Reply by uhlhosting** [reply]
It seems a issue could be that their system wants to validate the email username in form of an email@domain.tld , and since postal uses own naming is not working. what is however weird, is that on their older versions this worked great.

**Reply by willpower232** [reply]
Postal doesn't care about what the SMTP_USERNAME is so you could type whatever you want in there, chatwoot@example.com for example.

MAILER_SENDER_EMAIL would need to be a real email address using a domain configured in Postal.

**Reply by uhlhosting** [reply]
Good to know!

**Reply by uhlhosting** [reply]
Now we got another error: `2022-04-06T11:33:14.081841007Z E, [2022-04-06T11:33:14.081662 #1] ERROR -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [84e29fa0-2c49-4c0d-b36a-fb0227e6c8fe] Error performing ActionMailer::MailDeliveryJob (Job ID: 84e29fa0-2c49-4c0d-b36a-fb0227e6c8fe) from Sidekiq(mailers) in 14176.13ms: OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)):`

**Reply by willpower232** [reply]
Is that from chatwoot? presumably not in docker? it is what happens when SSL isn't quite installed properly in the system

**Reply by uhlhosting** [reply]
Yes thats from chatwoot, it does run in docker. Yet this is the workers logs, since the app its split in 4 docker parts.

**Comment by uhlhosting** [comment]
In my Postal logs I cannot see much but this;

```
smtp_1      | /usr/local/bundle/gems/gelf-3.0.0/lib/gelf/notifier.rb:65: warning: constant ::Fixnum is deprecated
smtp_1      | log writing failed. "\xFC" from ASCII-8BIT to UTF-8
smtp_1      | log writing failed. "\x89" from ASCII-8BIT to UTF-8
```

Here is current config we use:

```
smtp_server:
  port: 25
  tls_enabled: true
#  tls_certificate_path: "/caddy-data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/post.uhlhosting.ch/post.uhlhosting.ch.pem"
#  tls_private_key_path: "/caddy-data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/post.uhlhosting.ch/post.uhlhosting.ch-key.pem"
  tls_certificate_path: /config/fullchain.pem
  tls_private_key_path: /config/privkey.pem
  ssl_version: SSLv23
  proxy_protocol: false
  log_connect: true
  strip_received_headers: false
  max_message_size: 32 # size in Megabytes

smtp_relays:
  -
    hostname:
    port: 25
    ssl_mode: Auto
```

Here is my ChatWoot config:

<img width="709" alt="image" src="https://user-images.githubusercontent.com/6324047/162219966-f78cb38f-8294-4355-9e7e-b01c4c286ae7.png">


When running: 

I have tried without any TLS specified, any ideas what could cause this? I am using default caddy certificate generated.

```
root@btc:~/btcpayserver-docker# echo|openssl s_client -connect post.uhlhosting.ch:25 -starttls smtp -tls1_3|head -n 7
depth=0 CN = post.uhlhosting.ch
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = post.uhlhosting.ch
verify error:num=21:unable to verify the first certificate
verify return:1
250 AUTH CRAM-MD5 PLAIN LOGIN
DONE
CONNECTED(00000003)
---
Certificate chain
 0 s:CN = post.uhlhosting.ch
   i:C = US, O = Let's Encrypt, CN = R3
---
Server certificate
```

https://www.ssllabs.com/ssltest/analyze.html?d=post.uhlhosting.ch
