### DISCUSSION TITLE
Bind SMTP service to both public IPv4 and IPv6

### DISCUSSION THREAD

**Discussion by Joe-Ng-1998** [postalserver/postal#1980] [Help with using Postal]
After installing spamassassin, I found that exim4 is introduced and listens on localhost:25 and ip6-localhost:25

```
lsof -i :25
COMMAND  PID        USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
exim4   1081 Debian-exim    4u  IPv4  19465      0t0  TCP localhost:smtp (LISTEN)
exim4   1081 Debian-exim    5u  IPv6  19466      0t0  TCP ip6-localhost:smtp (LISTEN)
```

In this case, binding to all IPs will fail, since port 25 on localhost is taken by exim4. See the YAML config below.

```
smtp_server:
  # Specify configuration to the Postal SMTP server
  bind_address: '::'
  port: 25
```

How do I configure postal.yml to make smtp service listen on both public IPv4 and IPv6?
