### DISCUSSION TITLE
Incoming messages not working

### DISCUSSION THREAD

**Discussion by toto1384** [postalserver/postal#2028] [Help with using Postal]
So, this are my records
<img width="1487" alt="Screenshot 2022-06-18 at 17 28 49" src="https://user-images.githubusercontent.com/35605914/174443276-9112f8e6-9d9f-4734-b907-ce991b42c2e0.png">

The server sees the records as good
<img width="604" alt="Screenshot 2022-06-18 at 17 38 53" src="https://user-images.githubusercontent.com/35605914/174443315-47bec1b0-cd42-4c71-b6ab-436bf81c12d0.png">

Here is my config file
```
general:
  # This can be changed to allow messages to be sent from multiple IP addresses
  use_ip_pools: false

web:
  # The host that the management interface will be available on
  host: postal.goodjobs.ro
  # The protocol that requests to the management interface should happen on
  protocol: https

web_server:
  # Specify configuration for the Postal web server
  bind_address: 127.0.0.1
  port: 5000

smtp_server:
  # Specify configuration to the Postal SMTP server
  port: 587
  tls_enabled: true
  #tls_ciphers:
          #ssl_version: TLSv1
          #proxy_protocol: true
          #log_connect: true
          #strip_received_headers: false
          #max_message_size: 14

logging:
  # Specify options for the logging
  stdout: true

main_db:
  # Specify the connection details for your MySQL database
  host: 127.0.0.1
  username: postal
  password: <password>
  database: postal

message_db:
  # Specify the connection details for your MySQL server that will be house the
  # message databases for mail servers.
  host: 127.0.0.1
  username: postal
  password: <password>
  prefix: postal

rabbitmq:
  # Specify connection details for your RabbitMQ server
  host: 127.0.0.1
  username: postal
  password: <password>
  vhost: postal

dns:
  # Specify the DNS records that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - postal.goodjobs.ro
  smtp_server_hostname: postal.goodjobs.ro
  spf_include: spf.postal.goodjobs.ro
  return_path: rp.postal.goodjobs.ro
  route_domain: routes.postal.goodjobs.ro
  track_domain: postal.goodjobs.ro

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 127.0.0.1
  port: 587
  username: # Complete when Postal is running and you can
  password: # generate the credentials within the interface.
  from_name: Postal
  from_address: postal.goodjobs.ro

rails:
  # This is generated automatically by the config initialization. It should be a random
  # string unique to your installation.
  secret_key: <secretkey>

```

Keep in mind that I am new to SMTP servers
