### DISCUSSION TITLE
Setting up a difficult SSL/TLS certificate for the SMTP server

### DISCUSSION THREAD

**Discussion by JanesDev** [postalserver/postal#2129] [Help with using Postal] [answered]
For practice a day I try to put a TLS / SSL certificate on the smtp server of Postal but the server always returns the same error which is:
![image](https://user-images.githubusercontent.com/112242822/187058254-27dad9a5-4391-4948-ad7a-e836f3727baf.png)

After reading some discussions here on github, I started looking for the error in the smtp logs and there I realized that it could not find the path to the ssl certificate
![image](https://user-images.githubusercontent.com/112242822/187058447-f4eda28f-d288-4858-86c3-6c17281f0074.png)

yet the SSL certificate is beautiful and well present. From there I tried various things but the server reports that it cannot find the path to the certificate.

I would like some help please.

Thanks

**Comment by kluvi** [comment, marked as answer]
I just set up this yesterday and it worked. I have 2 tips which you can try:

1) Does both files have correct owner? Postal inside container runs with UID=GID=999, so certificates must be readable by this user

2) The path in log file looks weird... I think it should be in config directory, because this file is mounted inside container :thinking: 
postal.yml:
   ```
   smtp_server:
     port: 25
     tls_enabled: true
     tls_certificate_path: /config/smtp.cert
     tls_private_key_path: /config/smtp.key
   ```
