### DISCUSSION TITLE
Postall isntall tracking (Tracking not working)

### DISCUSSION THREAD

**Discussion by Dmit84** [postalserver/postal#2268] [Help with using Postal] [answered]
**Tracking not working** on click.domain1.com

postal.yml
```
general:
  # This can be changed to allow messages to be sent from multiple IP addresses
  use_ip_pools: true

web:
  # The host that the management interface will be available on
  host: postal.domain.tech
  # The protocol that requests to the management interface should happen on
  protocol: https

web_server:
  # Specify configuration for the Postal web server
  bind_address: 127.0.0.1
  port: 5000

smtp_server:
  # Specify configuration to the Postal SMTP server
  port: 25

logging:
  # Specify options for the logging
  stdout: true

main_db:
  # Specify the connection details for your MySQL database
  host: 127.0.0.1
  username: postal
  password: eo8
  database: postal

message_db:
  # Specify the connection details for your MySQL server that will be house the
  # message databases for mail servers.
  host: 127.0.0.1
  username: postal
  password: eo8
  prefix: postal

rabbitmq:
  # Specify connection details for your RabbitMQ server
  host: 127.0.0.1
  username: postal
  password: ees
  vhost: postalvhost

dns:
  # Specify the DNS records that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - postal.domain.tech
  smtp_server_hostname: postal.domain.tech
  spf_include: spf.postal.domain.tech
  return_path: rp.postal.domain.tech
  route_domain: routes.postal.domain.tech
  track_domain: track.postal.domain.tech
  dkim_identifier: postal
  domain_verify_prefix: postal-verification
  custom_return_path_prefix: psrp

```

nginx
postal.domain.tech

```
server {
    listen 80;
    server_name postal.domain.tech;
    include acme.conf;
    location / {
        return 301 https://$host$request_uri;
    }
}


server {

    listen 443 ssl http2;
    ssl_certificate /etc/letsencrypt/live/postal.domain.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/postal.domain.tech/privkey.pem;

    server_name postal.domain.tech;
    include acme.conf;
    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Postal-Track-Host: 1;
    }
    access_log /var/log/nginx/postal.domain.tech.log;
}



server {
    listen 443 ssl;
    server_name click.domain1.com;
    ssl_certificate /etc/letsencrypt/live/click.domain1.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/click.domain1.com/privkey.pem; # managed by Certbot

    # Generate using: openssl dhparam 4096 -out /etc/ssl/dhparam.pem
    ssl_dhparam /etc/nginx/ssl/dhparam.pem;

    ssl_protocols TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA512:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:ECDH+AESGCM:ECDH+AES256:DH+AESGCM:DH+AES256:RSA+AESGCM:!aNULL:!eNULL:!LOW:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS;

    location / {
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Postal-Track-Host: 1;
        proxy_pass http://127.0.0.1:5000;
    }
}
```
