### DISCUSSION TITLE
Random SMTP Relay?

### DISCUSSION THREAD

**Discussion by metabinaryio** [postalserver/postal#2314] [Help with using Postal]
Hello,

After adding smtp_relays: - to the postal config file, the first relay host is always selected. Is it possible to randomly select hosts that have been added there after the dash?

```
smtp_relays:
  -
    hostname: server1.xxx.io
    port: 2525
    ssl_mode: Auto
  -
    hostname: de2.xxx.io
    port: 2525
    ssl_mode: Auto
  -
    hostname: gigantic.xxx.io
    port: 2525
    ssl_mode: Auto
```
