### DISCUSSION TITLE
DNS verification fluctuates

### DISCUSSION THREAD

**Discussion by emazelmaurya** [postalserver/postal#2383] [Help with using Postal]
Hi,

DNS verification fluctuates sometimes its shows "**DKIM & SPF configured correctly on 1 domain**" After some time it shows "**1 domain has misconfigured DNS records**". This is happening to one domain and another domain it is stable(different server). I have tweaked all DNS records, but it is still fluctuating. 

I want to know whether it is a server problem or a Postal Server issue.
it would be a great help to resolve.

Regards
Maurya

**Comment by willpower232** [comment]
You might need to change this value in case it is struggling to reach public DNS servers and Postal shows that as misconfigured

https://github.com/postalserver/postal/blob/87e9b3e3460c727d94f73d19368be0495799468c/config/postal.defaults.yml#L17

**Reply by emazelmaurya** [reply]
Hi @willpower232

No Lucky!  I have updated  
![nano](https://user-images.githubusercontent.com/128033164/226362844-03ffb439-1151-441f-a5d9-f0f367ebf59c.PNG)

**Reply by willpower232** [reply]
it is false by default so you might need to set it to true. you will also need to restart postal after making changes to this file.

**Reply by emazelmaurya** [reply]
Thanks, it worked.
![error](https://user-images.githubusercontent.com/128033164/226617403-ca158ca4-7da2-492c-9aeb-2cdbcf49ac9c.PNG)

The return path is not resolved
I have added the DNS record CNAME psrp.mydomainn.com to rp.postal.example.com.
It seems that Gmail is going for a hard fail

550-5.7.1 [49.204.67.76 12] Our system has detected that this message is 550-5.7.1 likely unsolicited mail. To reduce the amount of spam sent to Gmail, 550-5.7.1 this message has been blocked. Please visit 550-5.7.1 https://support.google.com/mail/?p=UnsolicitedMessageError 550 5.7.1 for more information. s6-20020a63ff46000000b005030a59a81dsi13154547pgk.159 - gsmtp

Mr. Will Power, please help me out.
Thanks In Advance

**Reply by willpower232** [reply]
if you're able to correct the return path, that would likely be helpful. otherwise you can try mail-tester.com to see what it thinks of your setup in case you have missed something.

If that doesn't help you with gmail then it might be something worse like a distrust of your IP/server provider which would require you to move to solve.

**Reply by emazelmaurya** [reply]
Thank you for your reply!

Tested with mail-tester.com
![mx](https://user-images.githubusercontent.com/128033164/227121018-dc9f0bf1-51c0-4594-8e9e-38b26a43b97d.PNG)

My Postal Server DNS Records is:

A records
postal.xxxxxx.com    49.67.204.77
rp.postal.xxxxxx.com 49.67.204.77

MX records
routes.postal.xxxxxx.com 10  postal.xxxxxx.com

TXT records
spf.postal.xxxxxx.com               "v=spf1 ip4:49.67.204.77 ~all"
rp.postal.xxxxxx.com	 	"v=spf1 a mx include:spf.postal.xxxxxxx.com ~all"
postal._domainkey.rp.postal.xxxxxxx.com	 	"v=DKIM1; t=s; h=sha256; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC2m5VlfUVt5i8EugUGYJxVKK4Q73wFntSH5ttRv4Bkl+aNeLjGmCwz1BgRFOM5kpMG+itaI8fpNxBmwH2c9P6eDs/ICJuYZ2uMGVAylDOjKmi8Ot8UuNHH746B3YsfpsS0AB9J0vSkwh/zVi2efw1ARVk+w/MnjOB6QTpqxB7HRQIDAQAB;"	
Kindly check for any mistake in doing.

**Reply by willpower232** [reply]
The documentation is apparently missing that you need an MX record on the return path, in your case it would be a copy of the routes.postal one.

**Reply by emazelmaurya** [reply]
Mr. Will Power

Thank you very much it got resolved! 
I add another MX record **rp.postal.xxxxx.com MX 10 postal.xxxxxxx.com**

Email scoring is 10/10

**Reply by emazelmaurya** [reply]
hi,
I am getting scoring 9.9/10 on mail-tester.com but I am getting hard fails on all Gmail ids.

550-5.7.1 [49.204.67.76 12] Our system has detected that this message is 550-5.7.1 likely unsolicited mail. To reduce the amount of spam sent to Gmail, 550-5.7.1 this message has been blocked. Please visit 550-5.7.1 https://support.google.com/mail/?p=UnsolicitedMessageError 550 5.7.1 for more information. a3-20020a170902ecc300b001a1e782c0c4si19468391plh.286 - gsmtp

I was checking all factors and I found that my postal server IP is Blacklisted by UCEPROTECTL2 & UCEPROTECTL3 is it because blacklisted Gmail is blocking the email or any other factors, I am not able to figure out.

Suggest me!

**Reply by willpower232** [reply]
You would have to contact those lists to find out what is the problem and what the resolution might be.

**Comment by aledavidgueva** [comment]
I have the same problem. Any idea?
Failed using `use_local_ns_for_domains: false` and `use_local_ns_for_domains: true`
The installation is clean. I try two times with new installations and the problem continue.

Sometimes fail SPF, sometimes DKIM. The provider of DNS is cloudflare.

This is my config YAML
```yml
general:
  use_ip_pools: false
  use_local_ns_for_domains: true # failed with default 'false' too

web:
  host: appsrv101.wandu.net.ar
  protocol: https

web_server:
  bind_address: 127.0.0.1
  port: 5000

smtp_server:
  port: 25
  tls_enabled: true
  tls_certificate_path: /config/certs/appsrv101.wandu.net.ar/fullchain.pem
  tls_private_key_path: /config/certs/appsrv101.wandu.net.ar/privkey.pem

logging:
  stdout: true

main_db:
  host: 127.0.0.1
  username: xxxxx
  password: xxxxx
  database: postal

message_db:
  host: 127.0.0.1
  username: xxxxx
  password: xxxxx
  prefix: postal

rabbitmq:
  host: 127.0.0.1
  username: xxxxx
  password: xxxxx
  vhost: postal

dns:
  mx_records:
    - appsrv101.wandu.net.ar
  smtp_server_hostname: appsrv101.wandu.net.ar
  spf_include: spf.appsrv101.wandu.net.ar
  return_path: rp.appsrv101.wandu.net.ar
  route_domain: routes.appsrv101.wandu.net.ar
  track_domain: track.appsrv101.wandu.net.ar
  dkim_identifier: appsrv101
  domain_verify_prefix: appsrv101-verification
  custom_return_path_prefix: appsrv101-rp
  
smtp:
  host: 127.0.0.1
  port: 2525
  username: # Complete when Postal is running and you can
  password: # generate the credentials within the interface.
  from_name: Postal
  from_address: appsrv101.wandu.net.ar

rails:
  secret_key: xxxxx
```

Postal server: appsrv101.wandu.net.ar
Domain of client: tufic-helados.com

May be is possible disable auto-check DNS in the cron? The problem is that when fail DKIM, the mails are not signed and are rejected. The records are OK, but auto check fail... Manual check from the ui works immediately.

In the server, `dig TXT tufic-helados.com` works always. Now is working, but fluctuate...

Thanks for your help!
