### DISCUSSION TITLE
NginX reverse proxy in front of postal doesn't seemt to work properly

### DISCUSSION THREAD

**Discussion by ghevge** [postalserver/postal#2574] [Help with using Postal]
I've managed to set up postal web console on my sysmte and was able to access it direcly (like pointint to the ip of the web instance).

Now I want to set up a reverse proxy (nginx) in front of it, which proxy will take care of the ssl/tls certificate. 
But my problem is that once I set up this proxy, I am able to get the postal login page, but when I try to log in i get a 422 error as follows:

```

web_1       | [9] [2023-08-11T00:13:24.642] INFO -- : Started POST "/login" for 192.168.1.2 at 2023-08-11 00:13:24 +0000
web_1       | [9] [2023-08-11T00:13:24.643] INFO -- : Processing by SessionsController#create as HTML
web_1       | [9] [2023-08-11T00:13:24.643] INFO -- :   Parameters: {"authenticity_token"=>"lCFiiWst1ztJsiTTZfsAKNV5HK8P8uikRrtfisc6mJ1Y02NlOowLb0Q+zrXViPfvFhFTNiRgHAEi7FemqzYbAA==", "return_to"=>"/", "email_address"=>"admin@mydomain.com", "password"=>"[FILTERED]", "commit"=>"Login"}
web_1       | [9] [2023-08-11T00:13:24.644] WARN -- : HTTP Origin header (https://postal.mydomain.com) didn't match request.base_url (http://postal.mydomain.com)
web_1       | [9] [2023-08-11T00:13:24.644] INFO -- : Completed 422 Unprocessable Entity in 1ms (ActiveRecord: 0.0ms | Allocations: 392)
web_1       | [9] [2023-08-11T00:13:24.645] FATAL -- :   
web_1       | ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
```

the postal yaml looks like this:

```
web:
  # The host that the management interface will be available on
  host: postal.mydomain.com
  # The protocol that requests to the management interface should happen on
  protocol: http

web_server:
  # Specify configuration for the Postal web server
  bind_address: 0.0.0.0
  port: 5001
```

Nginx reverse proxy conf:
```
............
server {
        #listen 443;
        server_name  postal.mydomain.com;

        location / {
	    proxy_http_version 1.1;
            #rewrite /postal/(.*) /$1 break;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            #proxy_set_header X-Forwarded-Proto https;
            proxy_pass http://192.168.1.99:5001;
        }
...................
```

I feel it is something to do with the postal login page redirection, but I'm not sure how to force postal to redirect to https and not http.

Any ideas?

Thanks
