### DISCUSSION TITLE
Initialize postal.

### DISCUSSION THREAD

**Discussion by Maligosus** [postalserver/postal#2588] [Help with using Postal] [answered]
After running docker containers, I try to initialize the postal database with the `postal initialize` command. The command throws an error that the `database 'postal' already exists.`
It cannot exist after volumes are removed.
I did docker `compose down -v` and ran `docker compose up` again and tried to run the postal initialize command again, and the same error was thrown again. Options -v remove all services volumes.
My compose file
```yml
version: "3.8"

services:
  mariadb:
    container_name: postal-mariadb
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: postal
      MARIADB_ROOT_PASSWORD: ******
    ports:
      - "127.0.0.1:3306:3306"

  rabbitmq:
    container_name: postal-rabbitmq
    image: rabbitmq:3.8
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: postal
      RABBITMQ_DEFAULT_PASS: ******
      RABBITMQ_DEFAULT_VHOST: postal
    ports:
      - "127.0.0.1:5672:5672"

  caddy:
    container_name: postal-caddy
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - /opt/postal/config/Caddyfile:/etc/caddy/Caddyfile
      - /opt/postal/caddy-data:/data
    network_mode: "host"

```
