### DISCUSSION TITLE
Postal reset password does not working SSL Issue

### DISCUSSION THREAD

**Discussion by inaz0** [postalserver/postal#2633] [Help with using Postal]
Hi all, 

Well i trying to make a password recovery with the postal web interface i have this error on the postal-web container : 

`postal-web-1  | OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 peeraddr=XXX.XXX.XXX.XXX:587 state=error: certificate verify failed (unable to get local issuer certificate)):`

I made this configuration for my postal.yml : 

```
smtp:
  host: myhost.cloud
  port: 587
  username: usernameTest
  password: passwordTestGeneratedByPostal
  from_name: Postal
  from_address: blah.cloud
```

And my smtp_server is configured to use 587 tls_enable and wildcard certificate was buy to a dedicated company (Gandi).

How to add the Root CA to the web-server ? Or other solution can ben make this feature work ?

Best regards
