### DISCUSSION TITLE
I cant see the WebUI - 502 Bad Gateway (using nginx instead of caddy)

### DISCUSSION THREAD

**Discussion by patchthecode** [postalserver/postal#2672] [Help with using Postal] [answered]
i have looked at all similar errors/discussions on this github project.
Is there anything I can try to debug the issue further?  I am especially interested if there is any command I can try locally to see if I can try something like `localhost:5000` to see if i can debug connecting the web issue further.

Here are the commands I have tried.
## Local checks

`docker compose -p postal ps`

<img width="594" alt="Screenshot 2023-10-23 at 4 42 38 PM" src="https://github.com/postalserver/postal/assets/2439146/89c0c81c-5e66-4cf9-9f46-eb103f6b1bc8">

## NGINX config
I am using Nginx. Here is my config. Its similar to what you have on the example with the exception of root commented out.
```
server {
    listen 80;
    server_name mail.threadscape.social;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen [::]:443 ssl;
    listen 0.0.0.0:443 ssl;

    # root /opt/postal/app/public;  # i commented this out because I dont have this folder and dont know what it is.

    server_name mail.threadscape.social;

    ssl_certificate /etc/nginx/ssl/live/threadscape.social/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/live/threadscape.social/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
    ssl_prefer_server_ciphers on;
    ssl_ciphers EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA512:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:ECDH+AESGCM:ECDH+AES256:DH+AESGCM:DH+AES256:RSA+AESGCM:!aNULL:!eNULL:!LOW:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS;
    
    location / {
       client_max_body_size 50M;
       try_files $uri $uri/index.html $uri.html @puma;
    }

    location /assets {
       add_header Cache-Control max-age=3600;
    }

    location @puma {
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://127.0.0.1:5000;
    }
}
```

## Postal.yml config

```
general:
  # This can be changed to allow messages to be sent from multiple IP addresses
  use_ip_pools: false

web:
  # The host that the management interface will be available on
  host: mail.threadscape.social
  # The protocol that requests to the management interface should happen on
  protocol: https

web_server:
  # Specify configuration for the Postal web server
  bind_address: 127.0.0.1
  port: 5000

smtp_server:
  # Specify configuration to the Postal SMTP server
  port: 25

logging:
  # Specify options for the logging
  stdout: true

main_db:
  # Specify the connection details for your MySQL database
  host: 127.0.0.1
  username: root
  password: postal
  database: postal

message_db:
  # Specify the connection details for your MySQL server that will be house the
  # message databases for mail servers.
  host: 127.0.0.1
  username: root
  password: postal
  prefix: postal

rabbitmq:
  # Specify connection details for your RabbitMQ server
  host: 127.0.0.1
  username: postal
  password: postal
  vhost: postal

dns:
  # Specify the DNS records that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - mx.mail.threadscape.social
  smtp_server_hostname: mail.threadscape.social
  spf_include: spf.mail.threadscape.social
  return_path: rp.mail.threadscape.social
  route_domain: routes.mail.threadscape.social
  track_domain: track.mail.threadscape.social

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 127.0.0.1
  port: 2525
  username: # Complete when Postal is running and you can
  password: # generate the credentials within the interface.
  from_name: Postal
  from_address: postal@yourdomain.com

rails:
  # This is generated automatically by the config initialization. It should be a random
  # string unique to your installation.
  secret_key: redacted
```
## Docker Compose file

```
version: "3.9"
services:
  web:
    image: ghcr.io/postalserver/postal:2.1.4
    command: postal web-server
    network_mode: host
    volumes:
      - ./config:/config

  smtp:
    image: ghcr.io/postalserver/postal:2.1.4
    command: postal smtp-server
    network_mode: host
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - ./config:/config

  worker:
    image: ghcr.io/postalserver/postal:2.1.4
    command: postal worker
    network_mode: host
    volumes:
      - ./config:/config

  cron:
    image: ghcr.io/postalserver/postal:2.1.4
    command: postal cron
    network_mode: host
    volumes:
      - ./config:/config

  requeuer:
    image: ghcr.io/postalserver/postal:2.1.4
    command: postal requeuer
    network_mode: host
    volumes:
      - ./config:/config

  runner:
    profiles: ["tools"]
    image: ghcr.io/postalserver/postal:2.1.4
    command: postal
    network_mode: host
    volumes:
      - ./config:/config
```

##  My docker desktop screen.

1. All the postal services are running in one container. 
2. Caddy is not running (im using nginx)
3. Rabbit and MariaDB is running

<img width="1277" alt="Screenshot 2023-10-23 at 5 07 12 PM" src="https://github.com/postalserver/postal/assets/2439146/1ff413ae-5ae1-49fa-9ad3-4f80851b66e7">

.

One thing i must note: You can see ports 3306, and 5572 exposed on docker, so that it can be accessed on the outside. 
However, with the Postal-web client, no ports is exposed. (maybe thats why it cant be connected to?)

While Postal is listening on port 5000 on the machine INSIDE the container, did it expose the port so that apps outside the container can talk to it?
