### DISCUSSION TITLE
SMTP Error - 530 From/Sender name is not valid.'

### DISCUSSION THREAD

**Discussion by f0sh** [postalserver/postal#2908] [Help with using Postal]
I recently set up postalserver in a isolated environment. I want to send emails from another host inside this network to postal. However I always get the error.

```javascript
Error sending email Error: Message failed: 530 From/Sender name is not valid
    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:790:19)
    at SMTPConnection._actionSMTPStream (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1706:34)
    at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1174:22)
    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:969:20)
    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:755:14)
    at SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:193:44)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10) {
  code: 'EMESSAGE',
  response: '530 From/Sender name is not valid',
  responseCode: 530,
  command: 'DATA'
}
```
If I use Mailhog instead in the same environment, the message is sucessfully received.
The email sent has the following header:

```
From: no-reply@otherdomain.tld
To: some-email@example.org
```

The sender is configured to use the following SMPT configuration:

```
      - SMTP_HOST=postal-smtp-1
      - SMTP_PORT=25
      - SMTP_SECURE=false
      - SMTP_USER=<user>
      - SMTP_PWD=<secret>
      - NOREPLY_EMAIL="no-reply@otherdomain.tld"
      - SUPPORT_EMAIL="support@domain.tld"
```
And I can see, that for the postalserver mailserver the SMTP credentials are working and the SMTP server got accessed. I also added `otherdomain.tld` as a domain there. Postalserver cannot access the internet and at the current state also shouldn't.

My configuration looks like

```yaml
version: 2

postal:
  web_hostname: mailer.domain.tld
  web_protocol: https
  smtp_hostname: mailer.domain.tld

main_db:
  host: mariadb
  username: postal
  password: <secret>
  database: postal

message_db:
  host: mariadb
  username: postal
  password: <secret>
  prefix: postal

smtp_server:
  default_port: 25
  default_bind_address: 0.0.0.0
  default_health_server_port: 9091 # The default port for the SMTP server health server to listen on
  default_health_server_bind_address: 0.0.0.0 # The default bind address for the SMTP server health server to listen on
  # Enable TLS for the SMTP server (requires certificate)
  tls_enabled: false
  # The path to the SMTP server's TLS certificate
  tls_certificate_path: $config-file-root/smtp.cert
  # The path to the SMTP server's TLS private key
  tls_private_key_path: $config-file-root/smtp.key
  # Override ciphers to use for SSL
  tls_ciphers: 
  # The SSL versions which are supported
  ssl_version: SSLv23
  # Enable proxy protocol for use behind some load balancers (supports proxy protocol v1 only)
  proxy_protocol: false
  # Enable connection logging
  log_connections: false
  # The maximum message size to accept from the SMTP server (in MB)
  max_message_size: 14
  # A regular expression to use to exclude connections from logging
  log_ip_address_exclusion_matcher: 

dns:
  # Specify the DNS records that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - mx1.mailer.domain.tld
  spf_include: mailer.domain.tld
  return_path_domain: mailer.domain.tld # The return path domain is the default domain that is used as the MAIL FROM for all messages sent
  route_domain: mailer.domain.tld # receive incoming e-mail by forwarding messages directly to routes in Postal
  track_domain: mailer.domain.tld # the domain for the links in emails to track clicks

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 127.0.0.1
  port: 25
  username: # Complete when Postal is running and you can
  password: # generate the credentials within the interface.
  from_name: Mailer
  from_address: technik@domain.tld

web_server:
  default_port: 5000
  default_bind_address: 0.0.0.0
  max_threads: 3

worker:
  default_health_server_port: 9090
  default_health_server_bind_address: 0.0.0.0
  threads: 2

rails:
  secret_key: <secret>
```

I don't know what I have configured wrong, so that it is not working. Has someone a hint or an idea what there could be the error?
Thanks.
