### DISCUSSION TITLE
Postal v3.3.2 SMTP server does not support TLS while using SMTP credentials

### DISCUSSION THREAD

**Discussion by techlawctopus** [postalserver/postal#2912] [Help with using Postal] [answered]
## Describe the bug

I generated SSL certificate using certbot, and enabled TLS by editing `postal.yml` with following config:

```
smtp_server:
  default_bind_address: "::"
  tls_enabled: true
  tls_certificate_path: /etc/letsencrypt/live/postal.example.com/fullchain.pem
  tls_private_key_path: /etc/letsencrypt/live/postal.example.com/privkey.pem

```
Mails sent with Postal web interface are successfully going through and they even say "Transport Security Received over an SSL connection", which is the expected behaviour.

But when I try to connect to SMTP server through external services, there is some issue during SSL handshake. 
If my postal server is running on postal.example.com then my SSL certificate is also for the same domain, i.e. postal.example.com (I had turned off the postal server for while until certbot standalone server generated the SSL certificate). 

My SMTP credentials still work with unencrypted messages, but I need to make it work with encrypted messages as well.

Not sure if this is due to some certificate issue (although postal web interface seems to be working fine with it), or is this due to the fact that port 25 does not support encrypted messages.

## Environment details 

 - OS: Ubuntu 22.04 LTS
