### DISCUSSION TITLE
docker compose ready to go

### DISCUSSION THREAD

**Discussion by mabed-fr** [postalserver/postal#2949] [Help with using Postal] [answered]
Bonjour,

I searched and almost found what I wanted to have a docker compose

I found the environment variable here: (is it ok for docker?) --> [ici](https://github.com/postalserver/postal/blob/d5104991903d42563c6c6f7ff01276d496e3304f/doc/config/environment-variables.md?plain=1#L7)

I have the following docker compose today

---

```
services:
  postal:
    image: ghcr.io/postalserver/postal:latest
    depends_on:
      - mariadb-postal
    volumes:
      - "/docker/volumes/mails/postal/config:/config"
    environment:
      POSTAL_SIGNING_KEY_PATH: /config/signing.key
      MAIN_DB_HOST: mariadb-postal
      POSTAL_WEB_HOSTNAME: postal.exemple.fr
      MAIN_DB_USERNAME: postal
      MAIN_DB_DATABASE: postal
      MAIN_DB_PASSWORD: eushie8ooRei0cee
      MESSAGE_DB_HOST: mariadb-postal
      MESSAGE_DB_USERNAME: postal
      MESSAGE_DB_PASSWORD: eushie8ooRei0cee
      LOGGING_ENABLED: "true"
      RAILS_ENVIRONMENT: production
      RAILS_LOG_ENABLED: "false"
      WAIT_FOR_TIMEOUT: 90
      WAIT_FOR_TARGETS: |-
        mariadb-postal:3306
    restart: always

  mariadb-postal:
    image: mariadb:latest
    volumes:
      - "/docker/volumes/mails/mariadb:/var/lib/mysql"
    environment:
      MARIADB_ROOT_PASSWORD: "test1"
      MARIADB_DATABASE: postal
      MARIADB_USER: postal
      MARIADB_PASSWORD: "test"
    restart: always
```

I find that the DOC on docker is thin

Can you help me ?
