### DISCUSSION TITLE
Sending messages not working

### DISCUSSION THREAD

**Discussion by justinjakull** [postalserver/postal#2979] [Help with using Postal] [answered]
Hi, everybody
So, I've setup everything according to the instuctions on the web, yet none of my test mails get send. Recieving messages works fine. In the logs of the SMTP-Server there is no evidence of a failed login or anything similar. 

Postal itself shows "excecution expired" for technical details. Every Message is a Soft Fail with message: "No SMTP servers were available for gmail.com. Tried gmail-smtp-in.l.google.com, alt1.gmail-smtp-in.l.google.com, alt2.gmail-smtp-in.l.google.com, alt3.gmail-smtp-in.l.google.com, and alt4.gmail-smtp-in.l.google.com."
The Postal worker logs: Cannot connect to 185.230.212.166:25 (mx2.zoho.eu) (Net::OpenTimeout: execution expired) log_id=DIDWRCGB component=worker thread=work1 original_queued_message=10 queued_message=10

Here's my postal.yml

``` yaml
version: 2

postal:
  web_hostname: postal.redacted.de
  web_protocol: https
  smtp_hostname: postal.redacted.de

main_db:
  host: 127.0.0.1
  username: root
  password: redacted
  database: postal

message_db:
  host: 127.0.0.1
  username: root
  password: redacted
  prefix: postal

smtp_server:
  default_bind_address: "::"
  port: 25

dns:
  # Specify the DNS records that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - mx.postal.redacted.de
  spf_include: spf.postal.redacted.de
  return_path_domain: rp.postal.redacted.de
  route_domain: routes.postal.redacted.de
  track_domain: track.postal.redacted.de

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 127.0.0.1
  port: 2525
  username: topogo/system
  password: redacted
  from_name: Postal
  from_address: postal.topogo.de

rails:
  # This is generated automatically by the config initialization. It should be a random
  # string unique to your installation.
  secret_key: redacted 
```
