### DISCUSSION TITLE
Run multiple smtp servers in postal v3

### DISCUSSION THREAD

**Discussion by gsommavilla** [postalserver/postal#3011] [Help with using Postal] [answered]
Hi, I'd like to run multiple smtp servers in postal.

In the docs https://docs.postalserver.io/other/containers I read that it is possible to "run multiple SMTP servers and load balance between them to add additional capacity for SMTP connections."

I am running postal v3 with a docker compose file like this:

```yaml
version: "3.9"
services:
  web:
  # ...
  # ...

  smtp:
    image: ghcr.io/postalserver/postal:3.3.3
    command: postal smtp-server
    network_mode: host
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - /opt/postal/config:/config
    restart: unless-stopped

# ...
```

and my configuration is based on the new format (like this: https://github.com/postalserver/postal/blob/main/doc/config/yaml.yml)

This may be a naive question but I have searched the documentation for a while without finding an answer.

How can I run multiple smtp servers in my postal installation?

**Comment by gsommavilla** [comment]
Also I would like to ask about replicating workers.

In the docs https://docs.postalserver.io/other/containers#the-workers)

I see that workers can be replicated:

"[The worker(s) (...) Command: postal worker (...) This runs a worker which will receive jobs from the message queue. Essentially, this handles processing all incoming and outgoing e-mail. If you're needing to process lots of e-mails, you may wish to run more than one of these. You can run as many of these as you wish."

Relevant excerpt of my docker-compose.yml:

```
version: "3.9"
services:
  web:
# ...
# ...

  worker:
    # image: ghcr.io/postalserver/postal:3.3.3
    image: repodocker.omitech.it:443/postalot:2024-04-22_11-48-14.bbb3e84
    command: postal worker
    network_mode: host
    volumes:
      - /opt/postal/config:/config
      - ./openssl-weak.cnf:/etc/ssl/openssl.cnf
    restart: unless-stopped
```

How can I create more than one worker?

Maybe creating a service called `worker2` in the docker compose yaml file with the same content of the `worker` service?

**Comment by willpower232** [comment, marked as answer]
You can make use of the `--scale` parameter to add more copies of containers, have a look at https://github.com/orgs/postalserver/discussions/2679 I think it is mentioned elsewhere but couldn't remember where

**Reply by gsommavilla** [reply]
That was extremely easy and elegant, thank you.

For the sake of completeness, it can be done "on the fly" (while the docker compose services are running), like this:
```
postal start --scale worker=8
```
or it can be embedded in the `/opt/postal/install/docker-compose.yml` file (so the 8 workers are spawned by default every time the docker env starts):
```
services:
  ...
  worker:
    image: ghcr.io/postalserver/postal:3.3.3
    restart: unless-stopped
    deploy:
      replicas: 8
    ...
```
