### DISCUSSION TITLE
WARNING: Using legacy config file format. Upgrade your postal.yml

### DISCUSSION THREAD

**Discussion by XenyFord** [postalserver/postal#3019] [Help with using Postal] [answered]
Hi Colleagues,

When upgraded my postal yesterday, it has been continuously giving below WARNING:

`Already up to date.
Re-executing upgrade script from pulled repository
No version specified, using latest available version...
Upgrading to 3.3.4
Pulling web    ... done
Pulling smtp   ... done
Pulling worker ... done
Creating postal_runner_run ... done
Loading config from /config/postal.yml
WARNING: Using legacy config file format. Upgrade your postal.yml to use
version 2 of the Postal configuration or configure using environment`

Can anyone kindly let me know on how to solve this? Thank you in advance!

**Comment by Goodzco** [comment]
Here is the structure of my yml file, hope this help :                                                                                                                                  
```
version: 2

postal:
  web_hostname: postal.domain.com
  web_protocol: https
  smtp_hostname: postal.domain.com

main_db:
  host: 127.0.0.1
  username:
  password: 
  database:

message_db:
  host: 127.0.0.1
  username: 
  password: 
  prefix:

smtp_server:
  listen:
    - 0.0.0.0:25
    - "::"
  #default_health_server_bind_address: 127.0.0.1
  tls_enabled: true
  tls_certificate_path: /etc/letsencrypt/...
  tls_private_key_path: /etc/letsencrypt/...
  ssl_version: SSLv23

dns:
  # Specify the DNS records that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - postal.domain.com
  spf_include: spf.postal.domain.com
  return_path_domain: rp.postal.domain.com
  route_domain: routes.postal.domain.com
  track_domain: track.postal.domain.com

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 127.0.0.1
  port: 465
  username: # Complete when Postal is running and you can
  password: # generate the credentials within the interface.
  from_name: name
  from_address: contact@domain.com
  
  rails:
  # This is generated automatically by the config initialization. It should be a random
  # string unique to your installation.
  secret_key: ********************************
```

**Reply by XenyFord** [reply]
Hi Sir,
Also, could you please help me on how to switch from caddy to Let'sencrypt SSL & TLS certificate for postal?

**Comment by willpower232** [comment]
As per [the docs](https://docs.postalserver.io/getting-started/upgrade-to-v3#configuration), there is an example of the new config file [in the repo](https://github.com/postalserver/postal/blob/main/doc/config/yaml.yml)

I think the code deals with both versions of the config file currently but if you do have some time to move over, future you will probably appreciate it!

**Reply by XenyFord** [reply]
Hi Mr. Will,
Do I need to replace the content of 'postal.yml' with the new format (v2)? Or do I also need to change the file name from 'postal.yml' to 'yaml.yml'? Thank you sir 🙏

**Reply by willpower232** [reply, marked as answer]
> Do I need to replace the content of 'postal.yml' with the new format (v2)?

Yes, you'll have to move your current values into their new places. Hopefully straightforward.

> do I also need to change the file name from 'postal.yml' to 'yaml.yml'? 

No the file name should remain the same. yaml.yml is just a complete example of what it should be.

**Reply by XenyFord** [reply]
Great!! A heartfelt thanks to you sir 🙏

**Reply by XenyFord** [reply]
Hi Sir,
I got below error, when I replaced the content of postal.yml into new format..

`Upgrading to 3.3.4
Pulling web    ... done
Pulling smtp   ... done
Pulling worker ... done
Creating postal_runner_run ... done
Loading config from /config/postal.yml
rake aborted!
Psych::SyntaxError: (<unknown>): found character that cannot start any token while scanning for the next token at line 53 column 1 (Psych::SyntaxError)
/opt/postal/app/lib/postal/config.rb:54:in `initialize_config'
/opt/postal/app/lib/postal/config.rb:185:in `<module:Postal>'
/opt/postal/app/lib/postal/config.rb:20:in `<top (required)>'
/opt/postal/app/config/boot.rb:7:in `require_relative'
/opt/postal/app/config/boot.rb:7:in `<top (required)>'
/opt/postal/app/config/application.rb:3:in `require_relative'
/opt/postal/app/config/application.rb:3:in `<top (required)>'
/opt/postal/app/Rakefile:6:in `require_relative'
/opt/postal/app/Rakefile:6:in `<top (required)>'
/usr/local/bundle/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/cli.rb:451:in `exec'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/cli.rb:28:in `start'
/usr/local/bundle/gems/bundler-2.5.6/exe/bundle:28:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.5.6/exe/bundle:20:in `<top (required)>'
/opt/postal/app/bin/bundle:108:in `load'
/opt/postal/app/bin/bundle:108:in `<main>'
(See full trace by running task with --trace)
ERROR: 1
`

**Reply by XenyFord** [reply]
Hi Sir,
Below is the complete content of my 'postal.yml' which is '/opt/postal/config/postal.yml'

```
version: 2

postal:

  web_hostname: postal.mydomain.com
  web_protocol: https
  smtp_hostname: postal.mydomain.com
  
 use_ip_pools: false
 default_maximum_delivery_attempts: 10
  
  # The number of days to hold a message before they will be expired
  default_maximum_hold_expiry_days: 5
  
  # The number of days an address will remain in a suppression list before being removed
  default_suppression_list_automatic_removal_days: 10
  
  # The default threshold at which a message should be treated as spam
  default_spam_threshold: 5
  
  # The default threshold at which a message should be treated as spam failure
  default_spam_failure_threshold: 20
  
  # Domain verification and checking usually checks with a domain's nameserver. Enable this to check with the server's local nameservers.
  use_local_ns_for_domain_verification: false
  
  # Append a Resend-Sender header to all outgoing e-mails
  use_resent_sender_header: true
  
  # Path to the private key used for signing
  signing_key_path: /config/server-rsa.key
  
  # An array of SMTP relays in the format of smtp://host:port
  smtp_relays: []
  
  # An array of IP addresses to trust for proxying requests to Postal (in addition to localhost addresses)
  trusted_proxies: []
  
  # The number of days after which to consider a lock as stale. Messages with stale locks will be removed and not retried.
  queued_message_lock_stale_days: 1
  
  # When enabled queued messages will be de-queued in batches based on their destination
  batch_queued_messages: true

web_server:
	
  # The default port the web server should listen on unless overriden by the PORT environment variable
  default_port: 5000
  
  # The default bind address the web server should listen on unless overriden by the BIND_ADDRESS environment variable
  default_bind_address: 127.0.0.1
  
  # The maximum number of threads which can be used by the web server
  max_threads: 5

worker:
	
  # The default port for the worker health server to listen on
  default_health_server_port: 9090
  
  # The default bind address for the worker health server to listen on
  default_health_server_bind_address: 127.0.0.1
  
  # The number of threads to execute within each worker
  threads: 8

main_db:
	
  # Hostname for the main MariaDB server
  host: localhost
  
  # The MariaDB port to connect to
  port: 3306
  
  # The MariaDB username
  username: root
  
  # The MariaDB password
  password: mypassword
	  
  # The MariaDB database name
  database: postal
  
  # The maximum size of the MariaDB connection pool
  pool_size: 5
  
  # The encoding to use when connecting to the MariaDB database
  encoding: utf8mb4

message_db:
	
  # Hostname for the MariaDB server which stores the mail server databases
  host: localhost
  
  # The MariaDB port to connect to
  port: 3306
  
  # The MariaDB username
  username: root
  
  # The MariaDB password
  password: mypassword
	  
  # The encoding to use when connecting to the MariaDB database
  encoding: utf8mb4
  
  # The MariaDB prefix to add to database names
  database_name_prefix: postal

logging:
	
  # Enable the default Rails logger
  rails_log_enabled: false
  
  # A DSN which should be used to report exceptions to Sentry
  sentry_dsn: 
	  
  # Enable the Postal logger to log to STDOUT
  enabled: true
  
  # Enable highlighting of log lines
  highlighting_enabled: false

gelf:
	
  # GELF-capable host to send logs to
  host: 
	  
  # GELF port to send logs to
  port: 12201
  
  # The facility name to add to all log entries sent to GELF
  facility: postal

smtp_server:
	
  # The default port the SMTP server should listen on unless overriden by the PORT environment variable
  default_port: 25
  
  # The default bind address the SMTP server should listen on unless overriden by the BIND_ADDRESS environment variable
  default_bind_address: ::
	  
  # The default port for the SMTP server health server to listen on
  default_health_server_port: 9091
  
  # The default bind address for the SMTP server health server to listen on
  default_health_server_bind_address: 127.0.0.1
  
  # Enable TLS for the SMTP server (requires certificate)
  tls_enabled: true
  
  # The path to the SMTP server's TLS certificate
  tls_certificate_path: /config/ssl.crt
  
  # The path to the SMTP server's TLS private key
  tls_private_key_path: /config/server-rsa.key
  
  # Override ciphers to use for SSL
  tls_ciphers: ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256
	  
  # The SSL versions which are supported
  ssl_version: SSLv23
  
  # Enable proxy protocol for use behind some load balancers (supports proxy protocol v1 only)
  proxy_protocol: false
  
  # Enable connection logging
  log_connections: false
  
  # The maximum message size to accept from the SMTP server (in MB)
  max_message_size: 14
  # A regular expression to use to exclude connections from logging
  log_ip_address_exclusion_matcher: 

dns:
	
  # The names of the default MX records
  mx_records:
    - postal.mydomain.com
	
  # The location of the SPF record
  spf_include: spf.postal.mydomain.com
  
  # The return path hostname
  return_path_domain: rp.postal.mydomain.com
  
  # The domain to use for hosting route-specific addresses
  route_domain: routes.postal.mydomain.com
  
  # The CNAME which tracking domains should be pointed to
  track_domain: track.postal.mydomain.com
  
  # The hostname to use in HELO/EHLO when connecting to external SMTP servers
  #helo_hostname: postal.mydomain.com
	  
  # The identifier to use for DKIM keys in DNS records
  dkim_identifier: epost
  
  # The prefix to add before TXT record verification string
  #domain_verify_prefix: epost-verification
  
  # The domain to use on external domains which points to the Postal return path domain
  #custom_return_path_prefix: psrp
  
  # The timeout to wait for DNS resolution
  timeout: 5
  
  # The path to the resolv.conf file containing addresses for local nameservers
  resolv_conf_path: /etc/resolv.conf

smtp:
  # The hostname to send application-level e-mails to
  host: 127.0.0.1
  # The port number to send application-level e-mails to
  port: 25
  # The username to use when authentication to the SMTP server
  username: 
  # The password to use when authentication to the SMTP server
  password: 
  # The type of authentication to use
  authentication_type: login
  # Use STARTTLS when connecting to the SMTP server and fail if unsupported
  enable_starttls: false
  # Detects if STARTTLS is enabled in the SMTP server and starts to use it
  enable_starttls_auto: true
  # When using TLS, you can set how OpenSSL checks the certificate. Use 'none' for no certificate checking
  openssl_verify_mode: peer
  # The name to use as the from name outgoing emails from Postal
  from_name: Postal
  # The e-mail to use as the from address outgoing emails from Postal
  from_address: epost@mydomain.com

rails:
  # The Rails environment to run the application in
  environment: production
  # The secret key used to sign and encrypt cookies and session data in the application
  secret_key: 3338db7a7ae789dc446e4125c73fac32edc4febc0c146b80ad51a989e373e2b424ae461c1a373553d5ae1fa4e2836b332e86cca255b6b2df732879343f4efc6e5722fd08c00dc3a4a8e59a5f27c72c99ba15031abbd058a3780d18222bf644059f9b014e0766217b2b40a88a035c0c272cf549e4be4fbab30c5de759a041dd08

rspamd:
  # Enable rspamd for message inspection
  enabled: false
  # The hostname of the rspamd server
  host: 127.0.0.1
  # The port of the rspamd server
  port: 11334
  # Enable SSL for the rspamd connection
  ssl: false
  # The password for the rspamd server
  password: 
  # Any flags for the rspamd server
  flags: 

spamd:
  # Enable SpamAssassin for message inspection
  enabled: false
  # The hostname for the SpamAssassin server
  host: 127.0.0.1
  # The port of the SpamAssassin server
  port: 783

clamav:
  # Enable ClamAV for message inspection
  enabled: false
  # The host of the ClamAV server
  host: 127.0.0.1
  # The port of the ClamAV server
  port: 2000

smtp_client:
  # The open timeout for outgoing SMTP connections
  open_timeout: 30
  # The read timeout for outgoing SMTP connections
  read_timeout: 30

migration_waiter:
  # Wait for all migrations to run before starting a process
  enabled: false
  # The number of attempts to try waiting for migrations to complete before start
  attempts: 120
  # The number of seconds to wait between each migration check
  sleep_time: 2

oidc:
  # Enable OIDC authentication
  enabled: false
  # When enabled, users with passwords will still be able to login locally. If disable, only OpenID Connect will be available.
  local_authentication_enabled: true
  # The name of the OIDC provider as shown in the UI
  name: OIDC Provider
  # The OIDC issuer URL
  issuer: 
  # The client ID for OIDC
  identifier: 
  # The client secret for OIDC
  secret: 
  # Scopes to request from the OIDC server.
  scopes:
    - openid,email
  # The field to use to determine the user's UID
  uid_field: sub
  # The field to use to determine the user's email address
  email_address_field: email
  # The field to use to determine the user's name
  name_field: name
  # Enable discovery to determine endpoints from .well-known/openid-configuration from the Issuer
  discovery: true
  # The authorize endpoint on the authorization server (only used when discovery is false)
  authorization_endpoint: 
  # The token endpoint on the authorization server (only used when discovery is false)
  token_endpoint: 
  # The user info endpoint on the authorization server (only used when discovery is false)
  userinfo_endpoint: 
  # The JWKS endpoint on the authorization server (only used when discovery is false)
  jwks_uri: 
```
