### DISCUSSION TITLE
Need some help configuring inbound emails

### DISCUSSION THREAD

**Discussion by ArtemStepanov** [postalserver/postal#3026] [Help with using Postal] [answered]
Hello community,

I need some assistance with configuring Postal to accept inbound mails. I'd like to use it as a "proxy" to forward mails from my domains to some specific email.

The problem is, that I cannot connect to SMTP. Also, SMTP checkers says that it's impossible to connect. I'll add some info.

Credentials were created. I tried to connect to postal.awocy.dev, and it resulted with timeout.

Containers are run in a host mode.

firewall

```
To                         Action      From
--                         ------      ----
Anywhere                   ALLOW       10.0.1.0/24               
25                         ALLOW       Anywhere                  
25 (v6)                    ALLOW       Anywhere (v6)             

10.0.1.100 443/tcp         ALLOW FWD   Anywhere                   # allow caddy 443/tcp web
10.0.1.100 80/tcp          ALLOW FWD   Anywhere                   # allow caddy 80/tcp web
```

postal.yaml

```yaml
version: 2

postal:
  web_hostname: postal.awocy.dev
  web_protocol: https
  smtp_hostname: postal.awocy.dev

main_db:
  host: 127.0.0.1
  username: root
  password: 
  database: postal

message_db:
  host: 127.0.0.1
  username: root
  password: 
  prefix: postal

smtp_server:
  default_bind_address: 0.0.0.0
  tls_enabled: true

dns:
  # Specify the DNS records that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - mx1.postal.awocy.dev
    - mx2.postal.awocy.dev
  spf_include: spf.postal.awocy.dev
  return_path_domain: rp.postal.awocy.dev
  route_domain: routes.postal.awocy.dev
  track_domain: track.postal.awocy.dev

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: postal.awocy.dev
  port: 25
  username: awocy/awocy-dev # Complete when Postal is running and you can
  password:  # generate the credentials within the interface.
  from_name: Postal
  from_address: postal.awocy.dev

rails:
  # This is generated automatically by the config initialization. It should be a random
  # string unique to your installation.
  secret_key: 

web_server:
  default_bind_address: 0.0.0.0
```

Caddyfile

```
postal.awocy.dev {
	reverse_proxy 10.0.0.1:5000
}

click.awocy.dev {
	reverse_proxy 10.0.0.1:5000 {
	header_up X-Postal-Track-Host "1"
  }
}
```

NS settings

```
;; A Records
*.awocy.dev.	1	IN	A	<hidden>
awocy.dev.	1	IN	A	<hidden>
mx1.postal.awocy.dev.	1	IN	A	<hidden>
mx2.postal.awocy.dev.	1	IN	A	<hidden>
postal.awocy.dev.	1	IN	A	<hidden>

;; AAAA Records
postal.awocy.dev.	1	IN	AAAA	<hidden>

;; CNAME Records
click.awocy.dev.	1	IN	CNAME	track.postal.awocy.dev.
psrp.awocy.dev.	1	IN	CNAME	rp.postal.awocy.dev.

;; MX Records
awocy.dev.	1	IN	MX	10 mx2.postal.awocy.dev.
awocy.dev.	1	IN	MX	10 mx1.postal.awocy.dev.
routes.postal.awocy.dev.	1	IN	MX	10 postal.awocy.dev.
rp.postal.awocy.dev.	1	IN	MX	10 postal.awocy.dev.

;; TXT Records
awocy.dev.	1	IN	TXT	"v=spf1 a mx include:spf.postal.awocy.dev ~all"
_dmarc.awocy.dev.	1	IN	TXT	"v=DMARC1;  p=quarantine; sp=quarantine; fo=0; adkim=r; aspf=r; pct=100; rf=afrf; ri=86400; rua=mailto:<hidden>"
postal._domainkey.rp.postal.awocy.dev.	1	IN	TXT	"v=DKIM1; t=s; h=sha256; p=<hidden>;"
postal-xk3ryh._domainkey.awocy.dev.	1	IN	TXT	"v=DKIM1; t=s; h=sha256; p=<hidden>;"
rp.postal.awocy.dev.	1	IN	TXT	"v=spf1 a mx include:spf.postal.awocy.dev ~all"
spf.postal.awocy.dev.	1	IN	TXT	"v=spf1 a mx ip4:<hidden> ip6:<hidden> ~all"
```

MXToolbox report

![image](https://github.com/postalserver/postal/assets/25004471/c2d7a264-7dd3-43ed-a122-ea700c9cde3d)

Configurration in Postal

![image](https://github.com/postalserver/postal/assets/25004471/517b7d91-bca3-4b79-b6bc-3c79a202cef0)

![image](https://github.com/postalserver/postal/assets/25004471/633e824c-b0d2-4c50-8f4d-ddc2326de847)

![image](https://github.com/postalserver/postal/assets/25004471/bea38491-89b7-435c-b64b-4977bfb4f6dd)

Sending works just correctly.
