### DISCUSSION TITLE
Spam checking does not work when messages are rejected by rspamd

### DISCUSSION THREAD

**Discussion by thedoom13** [postalserver/postal#3078] [Help with using Postal]
Hi, I am having problem with rspamd and need help.

## This is my configuration

I am running Postal v3 with 3 workers

```shell
postal status
```

| NAME            | IMAGE                             | COMMAND                | SERVICE | CREATED      | STATUS        | PORTS |
|-----------------|-----------------------------------|------------------------|---------|--------------|---------------|-------|
| postal-smtp-1   | ghcr.io/postalserver/postal:3.3.4 | "/docker-entrypoint.…" | smtp    | 24 hours ago | Up 24 minutes |
| postal-web-1    | ghcr.io/postalserver/postal:3.3.4 | "/docker-entrypoint.…" | web     | 24 hours ago | Up 24 minutes |
| postal-worker-1 | ghcr.io/postalserver/postal:3.3.4 | "/docker-entrypoint.…" | worker  | 24 hours ago | Up 24 minutes |
| postal-worker-2 | ghcr.io/postalserver/postal:3.3.4 | "/docker-entrypoint.…" | worker  | 24 hours ago | Up 24 minutes |
| postal-worker-3 | ghcr.io/postalserver/postal:3.3.4 | "/docker-entrypoint.…" | worker  | 24 hours ago | Up 24 minutes |

I installed rspamd on docker, using [tiredofit image](https://github.com/tiredofit/docker-rspamd) and using [clamav](https://hub.docker.com/r/clamav/clamav/) which is a module of rspamd

This is the content of the `docker-compose.yml` file for rspamd

```yaml
version: "3.9"
services:
  rspamd:
    image: tiredofit/rspamd
    restart: always
    ports:
      - "11333:11333"
      - "11334:11334"
    environment:
      CONTROLLER_PASS: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CLAMAV_HOST: clamav
      CLAMAV_PORT: 3310
      OLETOOLS_HOST: olefy
      OLETOOLS_PORT: 1055
    volumes:
      - /opt/postal/external/rspamd-data:/data/rspamd

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /opt/postal/external/redis-data:/data

  clamav:
    image: clamav/clamav
    restart: always
    ports:
      - "3310:3310"
      - "7357:7357"
    volumes:
      - /opt/postal/external/clam-data:/var/lib/clamav

  olefy:
    image: tiredofit/olefy
    restart: always
    ports:
      - "1055:1055"
```

I have enabled rspamd in `config/postal.yml`

```yaml
rspamd:
  enabled: true
  host: 127.0.0.1
  port: 11334
  ssl: false
  password: password
  flags:
```

I have set the Outgoing Spam Threshold value to 5

![image](https://github.com/user-attachments/assets/2b78b803-2f37-4c34-a6ec-97b1ea97b50c)

## These are the problems I am having

I sent a [Gtube](https://en.wikipedia.org/wiki/GTUBE) test spam email, mail is still being sent with the spam status as "Not spam". The spam check result is not displayed.

![image](https://github.com/user-attachments/assets/55c6cba1-e8ee-4836-b36d-4ca7ed14ed98)
![image](https://github.com/user-attachments/assets/662a9739-c240-4257-8daa-eab22f1406d6)

But I checked the rspamd log and found that the spam score is 15.

```shell
docker compose exec rspamd grep "20240731092101.XdxO3%test@mydomain.com" /logs/rspamd.log
```

>`2024-07-31 09:21:04 [notice] #2073(normal) <71029f>; task; rspamd_task_write_log: id: <20240731092101.XdxO3%test@mydomain.com>, qid: <oayN9sQCFmrg2DHJ>, ip: 123.45.67.89, from: <test@mydomain.com>, (default: S (reject): [15.00/15.00] [GTUBE(0.00){}]), len: 420, time: 132.582ms, dns req: 0, digest: <c369ae7ba6bc99afb4171b7e79b7eab4>, rcpts: <thedoom13@mydomain.net>, mime_rcpts: <thedoom13@mydomain.net>, forced: reject "Gtube pattern"; score=15.00 (set by GTUBE)`

In another case, I tried with [EICAR](https://en.wikipedia.org/wiki/EICAR_test_file) test email virus, Mail is still sent and blocked by Google SMTP Replay, not by Postal

![image](https://github.com/user-attachments/assets/cbc26890-8294-455a-adbd-794d24e08e03)
![image](https://github.com/user-attachments/assets/4a4e0475-cb48-4aa1-bf8d-f0036d0c6fe3)

But in the log rspamd rejected this mail

```shell
docker compose exec rspamd grep "20240731084117.WhvSs%test@mydomain.com" /logs/rspamd.log
```

>`2024-07-31 08:41:19 [notice] #2072(controller) <1fce7f>; csession; rspamd_task_write_log: id: <20240731084117.WhvSs%test@mydomain.com>, qid: <sI9wehQT4uXPDx55>, ip: 123.45.67.89, from: <test@mydomain.com>, (default: T (reject): [1.10/15.00] [MID_CONTAINS_FROM(1.00){},FISHY_TLD(0.10){mydomain.com;},MIME_GOOD(-0.10){multipart/mixed;text/plain;},RCVD_NO_TLS_LAST(0.10){},ARC_NA(0.00){},ASN(0.00){asn:131366, ipnet:123.45.67.89/24, country:UK;},CLAM_VIRUS(0.00){Eicar-Signature;},DISPOSABLE_ENVRCPT(0.00){mydomain.net;},DISPOSABLE_TO(0.00){mydomain.net;},FROM_EQ_ENVFROM(0.00){},FROM_NO_DN(0.00){},HAS_ATTACHMENT(0.00){},MIME_TRACE(0.00){0:+;1:+;2:+;},RCPT_COUNT_ONE(0.00){1;},RCVD_COUNT_ONE(0.00){1;},TO_DN_NONE(0.00){},TO_MATCH_ENVRCPT_ALL(0.00){}]), len: 1080, time: 650.743ms, dns req: 5, digest: <51f4406b8492fc1cf002f0f8282ff1d6>, rcpts: <thedoom13@mydomain.net>, mime_rcpts: <thedoom13@mydomain.net>, forced: reject "clamav: virus found: "Eicar-Signature""; score=nan (set by clamav)`
