### DISCUSSION TITLE
Default Port (25) Didn't Change After Enabling TLS

### DISCUSSION THREAD

**Discussion by emahdij** [postalserver/postal#3085] [Help with using Postal]
Hi everyone,
I've configured my SMTP settings in Postal as follows:
```
smtp_server:
  default_bind_address: "::"
  tls_enabled: true
  tls_certificate_path: /config/fullchain.pem
  tls_private_key_path: /config/privkey.pem
  tls_ciphers:
  ssl_version: SSLv23
```

I've enabled SSL, but I noticed Postal is still listing on port 25. Should I change it to port 583?

Thanks in advance for your help!
