### DISCUSSION TITLE
How to enable tls?

### DISCUSSION THREAD

**Discussion by i-am-henri** [postalserver/postal#3097] [Help with using Postal]
Hello 👋, 
I have a question about enabling tls. How exactly can I create a secured connection (I'm very new in this space)? I followed the docs, ran the command

```bash
openssl req -x509 -newkey rsa:4096 -keyout /opt/postal/config/smtp.key -out /opt/postal/config/smtp.cert -sha256 -days 365 -nodes
```

And added the option `tls_enabled: true` to my postal.yml file. But it's still not working? Maybe I forgot something?

**Comment by willpower232** [comment]
When you say it isn't working, what are you trying?

Did you restart Postal after updating the config file?

**Comment by i-am-henri** [comment]
Thank you for your message @willpower232  🙏. I restarted postal after changing my postal.yml file. I'm trying to send an email secured with this code:

```ts
import nodemailer from "nodemailer";

const transporter = nodemailer.createTransport({
    host: 'mail.selfmail.app',
    port: 25,
    secure: false,
    auth: {
        user: 'selfmail-smtp-user',
        pass: '...'
    }
});

const mailOptions = {
    from: 'henri <henri@selfmail.app>',
    to: '...',
    subject: '...',
    text: '...',
};

// Sende die E-Mail
transporter.sendMail(mailOptions, (error, info) => {
    if (error) {
        return console.log(error);
    }
});
```

I'm not sure which settings i should apply for the post and for the option `secured: ...`. Maybe is this the problem?

And this is my postal.yml config file:

```yml
version: 2

postal:
  web_hostname: mail.selfmail.app
  web_protocol: https
  smtp_hostname: mail.selfmail.app

main_db:
  host: 127.0.0.1
  username: root
  password: postal
  database: postal

message_db:
  host: 127.0.0.1
  username: root
  password: postal
  prefix: postal

smtp_server:
  default_bind_address: "::"
  tls_enabled: true

dns:
  # Specify the DNS records that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - mx.mail.selfmail.app
  spf_include: spf.mail.selfmail.app
  return_path_domain: rp.mail.selfmail.app
  route_domain: routes.mail.selfmail.app
  track_domain: track.mail.selfmail.app

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 127.0.0.1
  port: 2525
  username: # Complete when Postal is running and you can
  password: # generate the credentials within the interface.
  from_name: Postal
  from_address: mail.selfmail.app
 ```
