### DISCUSSION TITLE
web server doesn't respond unless overriding Host header

### DISCUSSION THREAD

**Discussion by myster-t** [postalserver/postal#3129] [Help with using Postal] [answered]
I followed the setup for postal using docker inside of an AWS Linux instance. Everything seems to be connected except the web server doesn't accept any web requests unless the header for Host is overwritten.

When I'm on the host server or within either the web or caddy dockers, either of these commands return the html page as expected: 
```
wget -O - --header=Host:postal.mydomain.com http://localhost:5000/login?return_to=%2F
curl -vvv -H 'Host:postal.mydomain.com' http://localhost:5000/login?return_to=%2F
```

However, if I don't override the `Host` header, then the web server 403s. For instance, from within the web docker:
```
$ wget http://localhost:5000/login?return_to=%2F
--2024-09-09 01:51:05--  http://localhost:5000/login?return_to=%2F
Resolving localhost (localhost)... 127.0.0.1, ::1
Connecting to localhost (localhost)|127.0.0.1|:5000... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-09-09 01:51:05 ERROR 403: Forbidden.
```

What exactly is causing this to happen? Is there a postal.yml config I need to set?

Separately, if this is how the world works, then what should I set in my Caddyfile to reverse proxy this correctly? I tried this, caddy gets the response and logs the request, but the web server 403s:
```
postal.mydomain.com {
  reverse_proxy 172.0.0.1:5000 {
    header_up Host "postal.mydomain.com"
  }
}
```

**Comment by willpower232** [comment]
There must be something wrong in your config file already, it should just work normally unless you have other proxies or something else in the way

https://github.com/postalserver/install/blob/main/examples/Caddyfile

What did you set as web_hostname under postal in your config file?

**Reply by myster-t** [reply]
it's extremely vanilla haha

```
version: 2

postal:
  web_hostname: postal.mydomain.com
  web_protocol: https
  smtp_hostname: postal.mydomain.com

main_db:
  host: postal.cluster.us-west-2.rds.amazonaws.com
  username: postal
  password: <password>
  database: postal_mydomain_com

message_db:
  host: postal.cluster.us-west-2.rds.amazonaws.com
  username: postal
  password: <password>
  prefix: postal_mydomain_com_msg

smtp_server:
  default_bind_address: "::"

dns:
  # Specify the DNS records that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - postal.mydomain.com
  spf_include: spf.postal.mydomain.com
  return_path_domain: rp.postal.mydomain.com
  route_domain: routes.postal.mydomain.com
  track_domain: track.postal.mydomain.com

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: postal.mydomain.com
  port: 25
  username: # Complete when Postal is running and you can
  password: # generate the credentials within the interface.
  from_name: Postal Management Services
  from_address: postal@mydomain.com

rails:
  # This is generated automatically by the config initialization. It should be a random
  # string unique to your installation.
  secret_key: <autogen secret>
```

i didn't really configure anything ¯\_(ツ)_/¯. i followed the instructions step by step. in fact, i even wrote down the steps i took so i can build a second postal server later:

```
# start aws linux t3a.medium with 30gb, postal vpc and postal keypair

yum install git jq
yum install docker
sudo mkdir -p /usr/local/lib/docker/cli-plugins/
sudo curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose

git clone https://github.com/postalserver/install /opt/postal/install
sudo ln -s /opt/postal/install/bin/postal /usr/bin/postal

service docker start

# update /opt/postal/config/postal.yml

postal initialize
postal make-user

postal start

docker run -d \
   --name postal-caddy \
   --restart always \
   --network host \
   -v /opt/postal/config/Caddyfile:/etc/caddy/Caddyfile \
   -v /opt/postal/caddy-data:/data \
   caddy
```

that's all i did and then i started debugging why the web ui wasn't accessible from my computer by testing if it was accessible from within the host shell. that's when i started testing with the `Host` header and trying out curls and wgets from within the host shell and the docker shells. it does seem everything's up and running (db's connected, ports are open, dns is set up, etc), but the web server is simply not responding to any requests without the `Host` header set to `postal.mydomain.com`
