### DISCUSSION TITLE
TLS not working

### DISCUSSION THREAD

**Discussion by plancked** [postalserver/postal#3202] [Help with using Postal] [answered]
Hi,

I cannot get TLS to work.
I've created a self-signed certificate using:
`openssl req -x509 -newkey rsa:4096 -keyout /opt/postal/config/smtp.key -out /opt/postal/config/smtp.cert -sha256 -days 365 -nodes`

and added the config:

```
smtp_server:
  default_bind_address: "::"
  tls_enabled: true
```

also tried:

```
smtp_server:
  default_bind_address: "::"
  tls_enabled: true
  tls_certificate_path: /opt/postal/config/smtp.cert
  tls_private_key_path: /opt/postal/config/smtp.key
```

But it just won't work, clients cannot connect using tls.

Thanks
Alex
