### DISCUSSION TITLE
Postal running image size growing and filling all the disk space

### DISCUSSION THREAD

**Discussion by GhaziTriki** [postalserver/postal#3234] [Help with using Postal] [answered]
## Describe the bug

Postal running for few weeks can take all the disk space and put the server down.

## To Reproduce

1. Keep it running with the default configuration

## Expected behaviour

Disk should be emptied at regular periods and never be fully filled by Postal

## Screenshots

The screenshot shows 10 days of Postal on a 64 GB drive.

![image](https://github.com/user-attachments/assets/fa8c732f-8f0c-4131-80f7-17a347a6ea08)

## Environment details 

 - OS: Ubuntu 24.04 LTS

## Additional information/context

I update my `docker-compose.yml` to the following content and things are now better. I am sure only Caddy should be concerned by the update, to be confirmed.

```yaml
services:
  web:
    image: ghcr.io/postalserver/postal:3.3.4
    command: postal web-server
    network_mode: host
    volumes:
      - /opt/postal/config:/config
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"

  smtp:
    image: ghcr.io/postalserver/postal:3.3.4
    command: postal smtp-server
    network_mode: host
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - /opt/postal/config:/config
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"

  worker:
    image: ghcr.io/postalserver/postal:3.3.4
    command: postal worker
    network_mode: host
    volumes:
      - /opt/postal/config:/config
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"

  runner:
    profiles: ["tools"]
    image: ghcr.io/postalserver/postal:3.3.4
    command: postal
    network_mode: host
    volumes:
      - /opt/postal/config:/config
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
```

Below 10 days of drive usage after the configuration update.

![image](https://github.com/user-attachments/assets/5d97c008-8984-43cf-b58b-fdcce359b60b)
