### DISCUSSION TITLE
Reduce attempts in postal Queue

### DISCUSSION THREAD

**Discussion by Talha5** [postalserver/postal#3267] [Help with using Postal] [answered]
How can i just reduce these attempts to like 2 or 3? 17 retries doesnt make sense to me. 

![Screenshot 2024-12-27 at 3 21 46 PM](https://github.com/user-attachments/assets/cae92e8e-52f5-4b48-b4e0-51ca82708f4b)

**Comment by willpower232** [comment]
It is controlled by this setting (or its environment variable equivalent)

https://github.com/postalserver/postal/blob/fd3c7ccdf6dc4ee0a76c9523cbd735159e4b8000/doc/config/yaml.yml#L13

The point is that, presuming you have guaranteed the email addresses you're sending to exist and are working, then it waits a bit longer between each attempt in the hope that whatever temporary issue is resolved but obviously that isn't always what happens.

**Reply by Talha5** [reply]
well my `postal.yml` looks like this:

```yaml
version: 2

postal:
  web_hostname: ******
  web_protocol: https
  smtp_hostname: ******

main_db:
  host: 127.0.0.1
  username: root
  password: postal
  database: postal

general:
  default_maximum_delivery_attempts: 1
  maximum_delivery_attempts: 1

message_db:
  host: 127.0.0.1
  username: root
  password: postal
  prefix: postal

smtp_server:
  max_attempts: 3
  default_bind_address: "::"

dns:
  # Specify the DNS records that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.

rails:
  # This is generated automatically by the config initialization. It should be a random
  # string unique to your installation.

```

The email address do exist
