### DISCUSSION TITLE
Cannot "Build a new mail server"

### DISCUSSION THREAD

**Discussion by everisk** [postalserver/postal#3295] [Help with using Postal]
On a fresh installation of Postal V3, I got error below. And it's showing on every page and when creating a new mail server, Postal returns error 500 [https://domain.com/servers].  Any help would be appreciated.

`Content-Security-Policy: The page’s settings blocked an event handler (script-src-attr) from being executed because it violates the following directive: “script-src 'self'” application-0dd293ea0a8f7f37880ae5bea4a4f1627195bd86b17430b7fb0313790f195df8.js:2:17674`

**Comment by willpower232** [comment]
> https://domain.com/servers

I don't think this is a page in Postal, what were you trying to see?

**Reply by everisk** [reply]
On that's just a dummy domain. I attached screenshot for reference.
![Screenshot 2025-02-10 161655](https://github.com/user-attachments/assets/f58eba17-4302-4cbb-b629-c64394750afd)

**Reply by willpower232** [reply]
I think this is the error when your database user can't make the new databases because you have to specify the database configuration twice in the configuration.

**Reply by everisk** [reply]
But I'm able to create an organization though. Below is my config. How do I check the error 500 log?

```
main_db:
  host: 127.0.0.1
  username: postalserver
  password: -
  database: postal

message_db:
  host: 127.0.0.1
  username: postalserver
  password: -
  prefix: postal
```
