### DISCUSSION TITLE
Example Grafana as json in the documentation and in the github repo

### DISCUSSION THREAD

**Discussion by arthurzenika** [postalserver/postal#3341] [Feature suggestions]
With version 2.x we developed some dashboards based on some metrics collected by sql_exporter https://github.com/justwatchcom/sql_exporter/  (see config in the comments below). This resulted in a dashboard that looks like this : 

![Screenshot from 2025-03-24 16-46-37](https://github.com/user-attachments/assets/be73bf6a-e4b2-4481-9efc-73841e799021)

With version 3.x and the native metrics can be collected and used in Grafana to add some more observability, this gives a (work-in-progress) dashboard that looks like this :  

![Screenshot from 2025-03-24 16-20-24](https://github.com/user-attachments/assets/d44efa84-7e82-4415-a82a-8e71d91003a3)

Would the project welcome a contribution with these dashboards ?

**Comment by arthurzenika** [comment]
The sql_exporter configuration looks like this : 

```
jobs:
  - name: "global"
    interval: '1m'
    connections:
      # do mysql command, then show databases to list postal-server-*&
      - 'mysql://${USER}:${PASSWORD}@tcp(127.0.0.1)/postal-server-1'
      - 'mysql://${USER}:${PASSWORD}@tcp(127.0.0.1)/postal-server-2'
    queries:
      - name: "postal_email"
        help: "Number of emails by status and outgoing/incoming"
        labels:
          - "Status"
          - "Scope"
        values:
          - "number"
        query:  |
          SELECT status as Status, scope as Scope, count(status) as number FROM messages GROUP BY status, scope;
      - name: "postal_suppressions"
        help: "Number of email addresses in suppression list"
        values:
          - "number"
        query:  |
          SELECT count(*) as number FROM suppressions;

```
