### DISCUSSION TITLE
Option for Automatic User Creation on First OIDC Login (JIT Provisioning)

### DISCUSSION THREAD

**Discussion by reyemb** [postalserver/postal#3347] [Feature suggestions]
Currently, when Postal is configured to use OpenID Connect (OIDC) for authentication (e.g., with Keycloak, Okta, etc.), users can only log in if their account already exists within Postal. If a user successfully authenticates against the OIDC provider but does not have a pre-existing account in Postal (matched either by a previously linked OIDC UID or by email address), the login fails, and they are typically redirected back to the login page.

This requires administrators to manually pre-provision user accounts in Postal for everyone who might need access via OIDC. This can be a significant administrative overhead, especially in larger organizations or environments where user access might be managed primarily through the central Identity Provider (IdP).

**Describe the solution you'd like**

Introduce a new configuration option within the oidc: section of postal.yml to enable automatic user creation upon the first successful OIDC login. For example:

# postal.yml

```yaml
oidc:
  enabled: true
  # ... other OIDC settings ...
  issuer: https://your-idp.com/auth/realms/your-realm
  identifier: postal-client-id
  secret: your-client-secret
  # New proposed option:
  auto_create_users: true  # Defaults to false if not specified
  # Optional: Define a default organization ID/name for auto-created users?
  # default_organization_id: 1
```

When oidc.auto_create_users is set to true:

1. A user authenticates via the configured OIDC provider for the first time.
2. Postal receives the callback with the user's authenticated details (UID, email, name, etc., based on uid_field, email_address_field, name_field mappings).
3. Postal checks if a user exists matching the OIDC UID or email address.
4. If no matching user is found, Postal automatically creates a new user account in its database.
5. The new user account is populated using the information received from the OIDC provider (at minimum, email and name).
6. The user's OIDC UID (sub or configured uid_field) is immediately linked to this newly created Postal account.
7. The user is successfully logged into Postal.
(Optional consideration for the feature: A way to specify a default organization or role for these automatically created users, or require admin approval/assignment after creation might be needed for practical security/management).
