### ISSUE TITLE
Failed to read SMTP TLS certificate

### ISSUE THREAD

**Issue by mdobydullah** [postalserver/postal#1511]
Hi, I set up Postal with docker (followed: https://docs.postalserver.io/) and added cert files to the postal.yml file.

```
smtp_server:
  tls_enabled: true
  tls_certificate_path: /opt/postal/config/smtp.crt
  tls_private_key_path: /opt/postal/config/smtp.key
```

Tested with: https://www.gmass.co/smtp-test

Results:
```
<< 250-My capabilities are
<< 250-STARTTLS
<< 250 AUTH CRAM-MD5 PLAIN LOGIN
>> STARTTLS
<< 220 Ready to start TLS
ERROR: An error occurred while attempting to establish an SSL or TLS connection.
```

Then I checked Postal SMTP log:

![ssl file not found](https://user-images.githubusercontent.com/13184472/127612232-bd5aff50-de9f-47ee-9d1d-dd573b0fcecf.png)

How can I solve this?
