### ISSUE TITLE
bundler: failed to load command: rake (/opt/postal/app/bin/rake): found character that cannot start any token

### ISSUE THREAD

**Issue by Hussienfahmy** [postalserver/postal#1836]
## Describe the bug
There is a bug leading to error in initialization when using passwords with symbols in postal.yml

For example
```
main_db:
  # Specify the connection details for your MySQL database
  host: 127.0.0.1
  username: root
  password: @password #the error message points to this line
  database: postal
```

## To Reproduce
Write password with symbols in postal.yml file then execute command 
postal initialize

## Expected behavior
Creating the database and tables

## What went wrong
```
[+] Running 5/5
 ⠿ smtp Pulled                                                                                                                                           0.6s
 ⠿ cron Pulled                                                                                                                                           0.6s
 ⠿ requeuer Pulled                                                                                                                                       0.6s
 ⠿ web Pulled                                                                                                                                            0.6s
 ⠿ worker Pulled                                                                                                                                         0.6s
Initializing database
bundler: failed to load command: rake (/opt/postal/app/bin/rake)
Psych::SyntaxError: (/config/postal.yml): found character that cannot start any token while scanning for the next token at line 43 column 13
  /usr/local/lib/ruby/2.6.0/psych.rb:456:in `parse'
  /usr/local/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
  /usr/local/lib/ruby/2.6.0/psych.rb:390:in `parse'
  /usr/local/lib/ruby/2.6.0/psych.rb:277:in `load'
  /usr/local/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
  /usr/local/lib/ruby/2.6.0/psych.rb:577:in `open'
  /usr/local/lib/ruby/2.6.0/psych.rb:577:in `load_file'
  /opt/postal/app/lib/postal/config.rb:61:in `yaml_config'
  /opt/postal/app/lib/postal/config.rb:31:in `config'
  /opt/postal/app/config/boot.rb:11:in `<top (required)>'
  /opt/postal/app/bin/rake:2:in `require_relative'
  /opt/postal/app/bin/rake:2:in `<top (required)>'
```

## The solution worked for me
I replace the password without symbols for example
```
main_db:
  # Specify the connection details for your MySQL database
  host: 127.0.0.1
  username: root
  password: password #password without wymbols
  database: postal
```
