### ISSUE TITLE
505 Bad Gateway Error. Provided details below

### ISSUE THREAD

**Issue by FreshImmuc** [postalserver/postal#1934]
502 Bad Gateway Error

![image](https://user-images.githubusercontent.com/65733898/160916488-b72b6d61-2dae-4586-a8ba-b32fd23c0404.png)

I set up NGINX reverse proxy to point to MYIP:5150

and my Postalserver config looks like this:
```
general:
  # This can be changed to allow messages to be sent from multiple IP addresses
  use_ip_pools: false

web:
  # The host that the management interface will be available on
  host: mail.XXX.net
  # The protocol that requests to the management interface should happen on
  protocol: https

web_server:
  # Specify configuration for the Postal web server
  bind_address: 127.0.0.1
  port: 5150

smtp_server:
  # Specify configuration to the Postal SMTP server
  port: 25

logging:
  # Specify options for the logging
  stdout: true

main_db:
  # Specify the connection details for your MySQL database
  host: 127.0.0.1
  username: postal
  password: XXX
  database: postal

message_db:
  # Specify the connection details for your MySQL server that will be house the
  # message databases for mail servers.
  host: 127.0.0.1
  username: postal
  password: XXX
  prefix: postal

rabbitmq:
  # Specify connection details for your RabbitMQ server
  host: 127.0.0.1
  username: postal
  password: postal
  vhost: postal

dns:
  # Specify the DNS records that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - mx.mail.XXX.net
  smtp_server_hostname: mail.XXX.net
  spf_include: spf.mail.XXX.net
  return_path: rp.mail.XXX.net
  route_domain: routes.mail.XXX.net
  track_domain: track.mail.XXX.net

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 127.0.0.1
  port: 2525
  username: # Complete when Postal is running and you can
  password: # generate the credentials within the interface.
  from_name: Postal
  from_address: mail.XXX.net

rails:
  # This is generated automatically by the config initialization. It should be a random
  # string unique to your installation.
  secret_key: XXX

```

I also tried to do it with caddy but also didn't work. This is my config for Caddy:

```
# Update this to match the hostname you wish to use for accessing the
# Postal web interface.
mail.XXX.net {
  reverse_proxy 127.0.0.1:5150
}

# If you use open/click tracking you may need to add additional hosts
# to this file using the format below.
#
# click.XXX.net {
#   reverse_proxy 127.0.0.1:5150 {
#     header_up X-Postal-Track-Host "1"
#   }
# }
```

I hope someone can help me with that.
