### ISSUE TITLE
Unable to send webhooks because of yaml_column_permitted_classes

### ISSUE THREAD

**Issue by Zdvori** [postalserver/postal#2476]
## Describe the bug
Notification domain return 403 unauthorized.
Webhooks not work.

## To Reproduce
1. Clean install of postal with docker will use ruby version 3.2.0.
2. add some domain

## Expected behaviour
Webhooks will work, notificat

## Screenshots
![obrazek](https://github.com/postalserver/postal/assets/134491012/c128dfcc-5bac-45bb-8a13-aab4ed037a59)

## Additional information/context
"403 unauthorized " should be solve by adding "config.hosts.clear" into app/config/environments/production.rb

**Comment by Zdvori** [comment]
both could be fixed by adding  lines to /opt/postal/environments/production.rb
```
  config.active_record.yaml_column_permitted_classes = [Symbol, Hash, Array, ActiveSupport::HashWithIndifferentAccess]
  config.hosts.clear
```

**Comment by catphish** [comment]
Please can you open a separate issue regarding the notification domain issue? Please explain what you mean by notification domain.

**Comment by Zdvori** [comment]
Under "Domains" ,  "[Tracking Domains]" add new domain,.... "click.example.com"

under /opt/postal/config/Caddyfile
i add
```
click.example.com {
   reverse_proxy 127.0.0.1:5000 {
     header_up X-Postal-Track-Host "1"
   }
}
```

send test email.... try click to email or display tracking pixel ... fails to 403 unauthorized.

**Comment by wehmoen** [comment]
Same issue with our installation. Tracking domains don't seem to work after upgrading to the latest version. I temporarily disabled them.

**Comment by Zdvori** [comment]
> Same issue with our installation. Tracking domains don't seem to work after upgrading to the latest version. I temporarily disabled them.

temporary could be fixed by adding "config.hosts.clear" into  /opt/postal/environments/production.rb
I copy locale copy app/config/environments folder into  /opt/postal/environments, add line "config.hosts.clear" 

and edit
/opt/postal/install/templates/docker-compose.yml 
```
version: "3.9"
services:
  web:
    image: ghcr.io/postalserver/postal:2.1.4
    command: postal web-server
    network_mode: host
    volumes:
      - /opt/postal/config:/config
      - /opt/postal/environments:/opt/postal/app/config/environments

```

**Comment by willpower232** [comment]
@catphish see #2415

**Comment by ashishtiwari1993** [comment]
Open and click webhook is still not triggering. Apart from this all webhooks  are working.

**Comment by alex-pommier** [comment]
I have the same problem. I edited 
/opt/postal/install/templates/docker-compose.yml

```
  GNU nano 4.8                                                                              docker-compose.yml
version: "3.9"
services:
  web:
    image: ghcr.io/postalserver/postal:2.1.4
    command: postal web-server
    network_mode: host
    volumes:
      - /opt/postal/config:/config
      - /opt/postal/environments:/opt/postal/app/config/environments

  smtp:
    image: ghcr.io/postalserver/postal:2.1.4
    command: postal smtp-server
    network_mode: host
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - /opt/postal/config:/config

  worker:
    image: ghcr.io/postalserver/postal:2.1.4
    command: postal worker
    network_mode: host
    volumes:
      - /opt/postal/config:/config
      - /opt/postal/environments:/opt/postal/app/config/environments

  cron:
    image: ghcr.io/postalserver/postal:2.1.4
    command: postal cron
    network_mode: host
    volumes:
      - /opt/postal/config:/config

  requeuer:
    image: ghcr.io/postalserver/postal:2.1.4
    command: postal requeuer
    network_mode: host
    volumes:
      - /opt/postal/config:/config

  runner:
    profiles: ["tools"]
    image: ghcr.io/postalserver/postal:2.1.4
    command: postal
    network_mode: host
    volumes:
      - /opt/postal/config:/config


Restarted postal but still tracking domains not working.
```
