### ISSUE TITLE
Postal doesn't automatically restart when host reboots (Docker installation)

### ISSUE THREAD

**Issue by majudev** [postalserver/postal#2741]
## Describe the bug

I have installed Postal using guide from https://docs.postalserver.io/install/prerequisites. It uses this repo: https://github.com/postalserver/install. After reboot I have to manually issue command `postal start` to start Postal, which in my opinion should happend automatically.

## To Reproduce

1. Install Postal on Debian 12 using official guide
2. Reboot the machine
3. Confirm Postal didn't start via `docker ps -a`

## Expected behaviour

I expect Postal to be in the same state as before reboot. This is quite typical with Docker setups.

## Environment details 

 - OS: Debian 12
 - Postal version: latest

## Possible fix

Change file `templates/docker-compose.yml` in the https://github.com/postalserver/install repo from:
```yaml
version: "3.9"
services:
  web:
    image: ghcr.io/postalserver/postal:{{version}}
    command: postal web-server
    network_mode: host
    volumes:
      - /opt/postal/config:/config

  smtp:
    image: ghcr.io/postalserver/postal:{{version}}
    command: postal smtp-server
    network_mode: host
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - /opt/postal/config:/config

  worker:
    image: ghcr.io/postalserver/postal:{{version}}
    command: postal worker
    network_mode: host
    volumes:
      - /opt/postal/config:/config

  cron:
    image: ghcr.io/postalserver/postal:{{version}}
    command: postal cron
    network_mode: host
    volumes:
      - /opt/postal/config:/config

  requeuer:
    image: ghcr.io/postalserver/postal:{{version}}
    command: postal requeuer
    network_mode: host
    volumes:
      - /opt/postal/config:/config

  runner:
    profiles: ["tools"]
    image: ghcr.io/postalserver/postal:{{version}}
    command: postal
    network_mode: host
    volumes:
      - /opt/postal/config:/config
```
to
```yaml
version: "3.9"
services:
  web:
    image: ghcr.io/postalserver/postal:{{version}}
    restart: unless-stopped
    command: postal web-server
    network_mode: host
    volumes:
      - /opt/postal/config:/config

  smtp:
    image: ghcr.io/postalserver/postal:{{version}}
    restart: unless-stopped
    command: postal smtp-server
    network_mode: host
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - /opt/postal/config:/config

  worker:
    image: ghcr.io/postalserver/postal:{{version}}
    restart: unless-stopped
    command: postal worker
    network_mode: host
    volumes:
      - /opt/postal/config:/config

  cron:
    image: ghcr.io/postalserver/postal:{{version}}
    restart: unless-stopped
    command: postal cron
    network_mode: host
    volumes:
      - /opt/postal/config:/config

  requeuer:
    image: ghcr.io/postalserver/postal:{{version}}
    restart: unless-stopped
    command: postal requeuer
    network_mode: host
    volumes:
      - /opt/postal/config:/config

  runner:
    profiles: ["tools"]
    image: ghcr.io/postalserver/postal:{{version}}
    restart: unless-stopped
    command: postal
    network_mode: host
    volumes:
      - /opt/postal/config:/config
```
