### ISSUE TITLE
v3 Breaking Changes: log files

### ISSUE THREAD

**Issue by McPizza0** [postalserver/postal#2864]
## Describe the bug

On v2, you're able to set the logging config with:
`stdout: false`
this would generate the logfiles which can be ingested by other systems such as `fail2ban`
https://github.com/postalserver/postal/blob/152633adfe861699fd7d762690d0c521c31d2dbf/lib/postal/config.rb#L100-L107

on v3, there was a large refactor to logging,
`stdout` was removed and a new config option was added instead: `enabled: false`
when set to false, logs are sent to `/dev/null` rather than a file
https://github.com/postalserver/postal/blob/4c27baee7ff554097c4a982c289dbbd4edc9db7a/lib/postal/config.rb#L76

this effectively breaks any bruteforce mitigation solutions that currently exist

## To Reproduce

1. install v3
2. set `logging` > `enabled: false` in config.yml
3. check container `/opt/postal/app/logs`

## Expected behaviour

expect to see a logfile named {servername}_server.log

**Comment by adamcooke** [comment]
Logging to files within containers is not a good practice and not supported in v3 - as you have found.

Docker itself will store these logs to a file on the host machine with appropriate rotation. You should look at ingesting these logs. You can find the path to a container's log file using something like this. 

```
docker inspect --format='{{.LogPath}} name-of-container
```

**Comment by adamcooke** [comment]
Do feel free to start a discussion under Feature Requests to add support for brute force protection directly in the SMTP server. 

This is functionality I would like to see without needing to use fail2ban.

**Comment by erichk4** [comment]
We are using the syslog logging driver provided by docker directly,
https://docs.docker.com/config/containers/logging/configure/#supported-logging-drivers

Below example will produce log files in /var/log/docker/postal-smtp.log 

docker-compose.yml

```
smtp:
    image: ghcr.io/postalserver/postal:3.1.1
    command: postal smtp-server
    network_mode: host
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - /opt/postal/config:/config
    restart: always
    logging:
      driver: syslog
      options:
        tag: "postal-smtp"   
```
and fail2ban:

jail.local:
```
[POSTAL]
enabled  = true
port     = 25
filter   = postal
maxretry = 3
findtime = 3600
logpath  = /var/log/docker/postal-smtp.log
```

filter.d > postal.conf

```
[Definition]
failregex = (.*)WARN   Authentication failure for <HOST>

ignoreregex =
```

**Comment by McPizza0** [comment]
@erichk4 tried this, didnt output any logs
will try doing a fresh install

**Comment by erichk4** [comment]
@McPizza0 
try: **postal stop** and then **postal start** (postal restart does not work)

**Comment by adamcooke** [comment]
If you can avoid making changes to your `docker-compose.yml` it will make upgrades easier. These configuration options should be able to be made globally which may be sufficient to redirect the logs. I haven't tried though.

**Comment by McPizza0** [comment]
correct way would be a docker-compose.override.yml with the following contents:
```yaml
version: "3.9"
services:
  smtp:
    logging:
      driver: syslog
      options:
        tag: "postal-smtp"
```
