### ISSUE TITLE
max_message_size in config doesn't seem to have an effect. stuck on 14MB when receiving mails

### ISSUE THREAD

**Issue by rakurtz** [postalserver/postal#3058]
I am also having issue not being abled to receive messages larger than 14 MB. I think i've set the correct config parameter and also checked, that the chunksize of the mariadb is big enough (set to 100 MB). 

I am using the current version of postal (3.3.4).

## my config
```
smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 127.0.0.1
  port: 2525
  username: xxxx
  password: xxxx
  from_name: Postal
  from_address: mydomain.com
  max_message_size: 50
```

## the error
this ist from the logs:
```
2024-07-26T10:47:50.671732+02:00 postal postal-smtp[869]: 2024-07-26 08:47:50 +0000 DEBUG  #033[34m=> 552 Message too large (maximum size 14MB)#033[0m trace_id=ENNYP98B component=smtp-server
```

these are the actual protocol messages (the client's view)
```
reply: b'552 Message too large (maximum size 14MB)\r\n'
reply: retcode (552); Msg: b'Message too large (maximum size 14MB)'
data: (552, b'Message too large (maximum size 14MB)')
send: 'rset\r\n'
reply: b'250 OK\r\n'
reply: retcode (250); Msg: b'OK'
send: 'QUIT\r\n'
reply: b'221 Closing Connection\r\n'
reply: retcode (221); Msg: b'Closing Connection'
An error occurred: (552, b'Message too large (maximum size 14MB)')
```

## what i tried 
1. restartet postal after adjusting the config file `postal stop && postal start` as well as `postal restart` (no difference)
2. in maria db: `SET GLOBAL max_allowed_packet=104857600;` (100 MB)

checked: 
```
MariaDB [(none)]> SHOW VARIABLES LIKE 'max_allowed_packet';
+--------------------+-----------+
| Variable_name      | Value     |
+--------------------+-----------+
| max_allowed_packet | 104857600 |
+--------------------+-----------+
1 row in set (0.002 sec)
```

any ideas on where to look or what measures to take?
