### ISSUE TITLE
Open & Link Tracking Documentation enhancement

### ISSUE THREAD

**Issue by igerzog** [postalserver/postal#321]
In case of local only access to postal management portal (eg. ssh proxy or openvpn) it is not necessary to bind extra static ip for this purpose. Sample config is:

- `/etc/nginx/sites-enabled/default`

```
server {
    listen 8080;
    server_name postal.example.com;
    return 301 https://$host:8443$request_uri;
}

server {
    listen 8443 ssl;
    root /opt/postal/app/public;
    server_name postal.example.com;
...
location / {
       client_max_body_size 50M;
       try_files $uri $uri/index.html $uri.html @puma;
    }

location /assets {
       add_header Cache-Control max-age=3600;
    }

location @puma {
       proxy_set_header X-Real-IP  $remote_addr;
       proxy_set_header Host $host:8443;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto https;
       proxy_pass http://127.0.0.1:5000;
    }
```
- `/opt/postal/config/postal.yml`

```
web:
  # The host that the management interface will be available on
  host: postal.example.com
  # The protocol that requests to the management interface should happen on
  protocol: https

fast_server:
  # This can be enabled to enable click & open tracking on emails. It is disabled by
  # default as it requires a separate static IP address on your server.
  enabled: true
  bind_address: 192.168.0.2 # the only internal static ip
...
smtp_server:
  tls_enabled: true
```
- `/etc/hosts` on your local machine (# ssh local port forwarding for 8443) 

```
...
127.0.0.1 postal.example.com
...
```

Fast server uses `80` and `443` ports by default and management portal can be accessed via `https://postal.example.com:8443`
